import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_POINT_6_PROMPTS: ImitationPrompt[] = [
  { id: "P261", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو أحد غلط عليه بكلمة بسيطة بيفترض حسن النية أول." },
  { id: "P262", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو جتكم دعوة فجأة يقدر يقرر بسرعة إذا يناسبه أو لا." },
  { id: "P263", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو أمامه جهاز أو أداة جديدة بيجربها بيده قبل يقرأ كل التعليمات." },
  { id: "P264", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو أول محاولة ما ضبطت بيغير الطريقة بدل يعيد نفسها." },
  { id: "P265", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو عندكم خيار مضمون وخيار ممتع شوي بيميل للممتع." },
  { id: "P266", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو سمع رأي مخالف له يسأل «ليش؟» قبل يرد." },
  { id: "P267", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو ما عرف جواب سؤال يعترف بسرعة بدل يخمّن بثقة." },
  { id: "P268", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو عنده مشكلة صغيرة يفضّل يحلها بنفسه قبل يطلب مساعدة." },
  { id: "P269", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو اكتشف طريقة أسهل لشغلة بيغير عادته القديمة." },
  { id: "P270", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو عنده قرار مهم ما يخليه لآخر الليل وهو تعبان." },
  { id: "P271", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو الخطة فشلت بيبدأ يفكر بالبديل بدل يلوم أحد." },
  { id: "P272", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو أحد انتقد فكرته بيأخذ المفيد ويترك الباقي." },
  { id: "P273", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو عندكم اختيار عشوائي بين مكانين بيوافق على القرعة فعلاً." },
  { id: "P274", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو ما يحب شي بالجَمعة بيقوله بلطف بدل يمشي مع الكل وهو منزعج." },
  { id: "P275", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو ظهرت معلومة جديدة تغير القرار بيغير رأيه بدون مشكلة." },
  { id: "P276", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو أمامه مهمة كبيرة يقسمها أجزاء صغيرة." },
  { id: "P277", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو احتاج يتعلم شي جديد بيسأل شخص مجرب أول." },
  { id: "P278", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو واحد قال له «ثق فيني» بيطلب تفاصيل إذا الموضوع مهم." },
  { id: "P279", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو عندكم وقت قليل يركز على المهم ويتجاهل الكماليات." },
  { id: "P280", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو انلغت خطة كان متحمس لها يطلع بديل لنفس اليوم." },
  { id: "P281", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو سووا له مفاجأة كبيرة بيتفاعل طبيعي بدون ما يتوتر." },
  { id: "P282", mode: "POINT", family: "personality-decisions", text: "أشر على اللي لو صار خلاف بسيط بينه وبين أحد يفضّل يحله بنفس اليوم." },
  { id: "P283", mode: "POINT", family: "social-gatherings", text: "أشر على اللي لو أحد من أهله طلب مشوار فجأة يحاول يرتب يومه عشان يساعد." },
  { id: "P284", mode: "POINT", family: "social-gatherings", text: "أشر على اللي لو فيه عزيمة عائلية بيتذكر يسلم على الكبار قبل ما يجلس." },
  { id: "P285", mode: "POINT", family: "social-gatherings", text: "أشر على اللي لو أحد من العائلة يحتاج رأي بشراء شي بيسأله عن استخدامه قبل يقترح." },
  { id: "P286", mode: "POINT", family: "social-gatherings", text: "أشر على اللي لو فيه طفل صغير بالجَمعة بيعرف يشغله بشي ممتع." },
  { id: "P287", mode: "POINT", family: "social-gatherings", text: "أشر على اللي لو رجع قريب من سفر بيسأله عن الرحلة قبل الهدايا." },
  { id: "P288", mode: "POINT", family: "social-gatherings", text: "أشر على اللي لو عندكم طبخة عائلية قديمة بيتحمس يعرف طريقتها." },
  { id: "P289", mode: "POINT", family: "social-gatherings", text: "أشر على اللي لو صار اختلاف على موعد العزيمة يدور وقت يناسب أغلب الناس." },
  { id: "P290", mode: "POINT", family: "social-gatherings", text: "أشر على اللي لو صورة عائلية قديمة طلعت بيعرف تقريبًا متى كانت." },
];
