import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_NUMBER_3_PROMPTS: ImitationPrompt[] = [
  { id: "N166", mode: "NUMBER", family: "travel-driving", text: "من 0 إلى 5، قد إيش تحب توقف بطريق السفر لمكان مو مخطط له؟" },
  { id: "N167", mode: "NUMBER", family: "travel-driving", text: "من آخر 5 أيام، كم يوم جلست برا وقت الغروب؟" },
  { id: "N168", mode: "NUMBER", family: "travel-driving", text: "من 0 إلى 5، قد إيش تفضّل السفر الصباح على الليل؟" },
  { id: "N169", mode: "NUMBER", family: "travel-driving", text: "من آخر 5 أيام، كم يوم استخدمت المواصلات بدل سيارتك؟" },
  { id: "N170", mode: "NUMBER", family: "travel-driving", text: "من 0 إلى 5، قد إيش تحب تزور أكثر من مكان بنفس الرحلة؟" },
  { id: "N171", mode: "NUMBER", family: "travel-driving", text: "من آخر 5 أيام، كم يوم أخذت معك جاكيت احتياط؟" },
  { id: "N172", mode: "NUMBER", family: "travel-driving", text: "من 0 إلى 5، قد إيش تستمتع بالمشي في حي جديد؟" },
  { id: "N173", mode: "NUMBER", family: "travel-driving", text: "من آخر 5 أيام، كم يوم اخترت مكان خارجي لأن الجو كان حلو؟" },
  { id: "N174", mode: "NUMBER", family: "travel-driving", text: "من 0 إلى 5، قد إيش تقدر تتحمل تأخير رحلة بدون ما يتعكر مزاجك؟" },
  { id: "N175", mode: "NUMBER", family: "travel-driving", text: "من آخر 5 أيام، كم يوم صورت منظر طبيعي؟" },
  { id: "N176", mode: "NUMBER", family: "travel-driving", text: "من 0 إلى 5، قد إيش تحب الطرق الطويلة بالسيارة؟" },
  { id: "N177", mode: "NUMBER", family: "planning-time", text: "من آخر 5 أيام، كم يوم خرجت قبل الموعد اللي حاطه لنفسك؟" },
  { id: "N178", mode: "NUMBER", family: "planning-time", text: "من 0 إلى 5، قد إيش تحب تعرف تفاصيل الخطة قبل توافق؟" },
  { id: "N179", mode: "NUMBER", family: "planning-time", text: "من آخر 5 أيام، كم يوم راجعت تقويمك أو جدولك؟" },
  { id: "N180", mode: "NUMBER", family: "planning-time", text: "من 0 إلى 5، قد إيش تحرص توصل قبل الموعد؟" },
  { id: "N181", mode: "NUMBER", family: "planning-time", text: "من آخر 5 أيام، كم يوم غيرت ترتيب مشاويرك عشان توفر وقت؟" },
  { id: "N182", mode: "NUMBER", family: "planning-time", text: "من 0 إلى 5، قد إيش تزعجك تغييرات الخطة بآخر لحظة؟" },
  { id: "N183", mode: "NUMBER", family: "planning-time", text: "من آخر 5 أيام، كم يوم كتبت قائمة مهام؟" },
  { id: "N184", mode: "NUMBER", family: "planning-time", text: "من 0 إلى 5، قد إيش تحب تخلص المهمات الصعبة أول؟" },
  { id: "N185", mode: "NUMBER", family: "planning-time", text: "من آخر 5 أيام، كم يوم جهزت شي من الليلة اللي قبل؟" },
  { id: "N186", mode: "NUMBER", family: "planning-time", text: "من 0 إلى 5، قد إيش تضيف وقت احتياط للزحمة؟" },
  { id: "N187", mode: "NUMBER", family: "planning-time", text: "من آخر 5 أيام، كم يوم خلصت شي قبل موعده؟" },
  { id: "N188", mode: "NUMBER", family: "planning-time", text: "من 0 إلى 5، قد إيش تحب يكون أسبوعك مخطط من البداية؟" },
  { id: "N189", mode: "NUMBER", family: "planning-time", text: "من آخر 5 أيام، كم يوم تذكرت موعد بدون أي تنبيه؟" },
  { id: "N190", mode: "NUMBER", family: "planning-time", text: "من 0 إلى 5، قد إيش تكون مرن إذا تغير جدولك فجأة؟" },
  { id: "N191", mode: "NUMBER", family: "planning-time", text: "من آخر 5 أيام، كم يوم تأخرت عن الوقت اللي قلته لشخص؟" },
  { id: "N192", mode: "NUMBER", family: "planning-time", text: "من 0 إلى 5، قد إيش تحب تحسم المكان قبل ما تطلع؟" },
  { id: "N193", mode: "NUMBER", family: "planning-time", text: "من آخر 5 أيام، كم يوم كان عندك وقت فاضي بسبب إلغاء أو تأجيل؟" },
  { id: "N194", mode: "NUMBER", family: "planning-time", text: "من 0 إلى 5، قد إيش تستفيد من الوقت الفاضي بين موعدين؟" },
  { id: "N195", mode: "NUMBER", family: "planning-time", text: "من آخر 5 أيام، كم يوم سويت أكثر من مشوار بنفس الطلعة؟" },
];
