import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_NUMBER_5_PROMPTS: ImitationPrompt[] = [
  { id: "N231", mode: "NUMBER", family: "music-media", text: "من آخر 5 أيام، كم يوم قرأت خبر أو مقال كامل؟" },
  { id: "N232", mode: "NUMBER", family: "music-media", text: "من 0 إلى 5، قد إيش يفرق معك تقييم الفيلم قبل تشوفه؟" },
  { id: "N233", mode: "NUMBER", family: "music-media", text: "من آخر 5 أيام، كم يوم أرسلت لأحد أغنية عجبتك؟" },
  { id: "N234", mode: "NUMBER", family: "sports-games", text: "من 0 إلى 5، قد إيش تتحمس لتجربة لعبة جديدة؟" },
  { id: "N235", mode: "NUMBER", family: "music-media", text: "من آخر 5 أيام، كم يوم شغلت موسيقى وأنت تسوي مهمة ثانية؟" },
  { id: "N236", mode: "NUMBER", family: "sports-games", text: "من 0 إلى 5، قد إيش تقدر تشوف مباراة بدون تمسك جوالك؟" },
  { id: "N237", mode: "NUMBER", family: "music-media", text: "من آخر 5 أيام، كم يوم أضفت فيلم أو مسلسل لقائمة المشاهدة؟" },
  { id: "N238", mode: "NUMBER", family: "music-media", text: "من 0 إلى 5، قد إيش تحب تسمع بودكاست بالمشاوير؟" },
  { id: "N239", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم بدأت سالفة مع شخص من نفسك؟" },
  { id: "N240", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش ترتاح بالجمعات الصغيرة؟" },
  { id: "N241", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم سلمت أو تكلمت مع شخص ما تعرفه زين؟" },
  { id: "N242", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تحب تكون أنت اللي يعرف الناس على بعض؟" },
  { id: "N243", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم جلست مع أحد وسمعت له أكثر مما تكلمت؟" },
  { id: "N244", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تنتبه إذا شخص بالجَمعة ساكت؟" },
  { id: "N245", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم عرضت مساعدة على أحد بدون ما يطلب؟" },
  { id: "N246", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تحب الألعاب الجماعية في القعدات؟" },
  { id: "N247", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم رديت على دعوة بنفس اليوم؟" },
  { id: "N248", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تقدر تفتح سالفة مع شخص جديد؟" },
  { id: "N249", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم كلمت شخص كنت مأجل تكلمه؟" },
  { id: "N250", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تفضل تحل الخلاف مباشرة بدل تسحبه؟" },
  { id: "N251", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم شاركت في ترتيب أو تجهيز جمعة؟" },
  { id: "N252", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تستمتع باستضافة الناس عندك؟" },
  { id: "N253", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم سألت أحد كيف حاله بشكل جدي؟" },
  { id: "N254", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تحب الزيارات القصيرة؟" },
  { id: "N255", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم ضحكت أو سولفت مع ناس من أكثر من دائرة تعرفها؟" },
  { id: "N256", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تحتاج وقت هادي بعد جمعة كبيرة؟" },
  { id: "N257", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم تذكرت تفصيلة قالها لك شخص قبل؟" },
  { id: "N258", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تحب تدخل الشخص الجديد في السالفة؟" },
  { id: "N259", mode: "NUMBER", family: "personality-decisions", text: "من آخر 5 أيام، كم يوم جربت طريقة جديدة لشي تسويه عادة؟" },
  { id: "N260", mode: "NUMBER", family: "personality-decisions", text: "من 0 إلى 5، قد إيش تحسم بين خيارين بسرعة؟" },
];
