import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_NUMBER_4_PROMPTS: ImitationPrompt[] = [
  { id: "N196", mode: "NUMBER", family: "planning-time", text: "من 0 إلى 5، قد إيش تفضل جدول مرن على جدول بالدقيقة؟" },
  { id: "N197", mode: "NUMBER", family: "planning-time", text: "من آخر 5 أيام، كم يوم راجعت شي قبل ما ترسله أو تسلمه؟" },
  { id: "N198", mode: "NUMBER", family: "planning-time", text: "من 0 إلى 5، قد إيش ترتاح إذا عرفت مدة المشوار قبل تبدأ؟" },
  { id: "N199", mode: "NUMBER", family: "shopping-money", text: "من آخر 5 أيام، كم يوم قررت ما تشتري شي بعد ما قارنت سعره؟" },
  { id: "N200", mode: "NUMBER", family: "shopping-money", text: "من 0 إلى 5، قد إيش تدور تقييمات قبل شراء شي غالي؟" },
  { id: "N201", mode: "NUMBER", family: "shopping-money", text: "من آخر 5 أيام، كم يوم اشتريت شي كان في قائمتك من قبل؟" },
  { id: "N202", mode: "NUMBER", family: "shopping-money", text: "من 0 إلى 5، قد إيش تفضل الأشياء العملية على الكماليات؟" },
  { id: "N203", mode: "NUMBER", family: "shopping-money", text: "من آخر 5 أيام، كم يوم استخدمت شي قديم بدل تشتري بديل جديد؟" },
  { id: "N204", mode: "NUMBER", family: "shopping-money", text: "من 0 إلى 5، قد إيش تنتظر التخفيض إذا الشي مو مستعجل؟" },
  { id: "N205", mode: "NUMBER", family: "shopping-money", text: "من آخر 5 أيام، كم يوم احتفظت بفاتورة شراء أو إيصال؟" },
  { id: "N206", mode: "NUMBER", family: "shopping-money", text: "من 0 إلى 5، قد إيش تحب تشوف المنتج بنفسك قبل تشتريه؟" },
  { id: "N207", mode: "NUMBER", family: "shopping-money", text: "من آخر 5 أيام، كم يوم دخلت متجر أو موقع وما اشتريت شي؟" },
  { id: "N208", mode: "NUMBER", family: "shopping-money", text: "من 0 إلى 5، قد إيش يهمك يكون للهدية استخدام فعلي؟" },
  { id: "N209", mode: "NUMBER", family: "home-routine", text: "من آخر 5 أيام، كم يوم رجعت غرض مكانه مباشرة بعد استخدامه؟" },
  { id: "N210", mode: "NUMBER", family: "home-routine", text: "من 0 إلى 5، قد إيش تحب الطاولات والأسطح تكون فاضية؟" },
  { id: "N211", mode: "NUMBER", family: "home-routine", text: "من آخر 5 أيام، كم يوم رتبت درج أو رف صغير؟" },
  { id: "N212", mode: "NUMBER", family: "home-routine", text: "من 0 إلى 5، قد إيش تحب تصلح الشي قبل تفكر تستبدله؟" },
  { id: "N213", mode: "NUMBER", family: "home-routine", text: "من آخر 5 أيام، كم يوم طويت ملابس بنفس اليوم؟" },
  { id: "N214", mode: "NUMBER", family: "home-routine", text: "من 0 إلى 5، قد إيش يريحك يكون لكل شي مكان ثابت؟" },
  { id: "N215", mode: "NUMBER", family: "home-routine", text: "من آخر 5 أيام، كم يوم نظفت وأنت تسمع موسيقى أو بودكاست؟" },
  { id: "N216", mode: "NUMBER", family: "home-routine", text: "من 0 إلى 5، قد إيش تتخلص بسهولة من الأشياء اللي ما تستخدمها؟" },
  { id: "N217", mode: "NUMBER", family: "home-routine", text: "من آخر 5 أيام، كم يوم فتحت الشباك أو الباب عشان تغير جو البيت؟" },
  { id: "N218", mode: "NUMBER", family: "home-routine", text: "من 0 إلى 5، قد إيش تحب ترتيب المكان قبل تبدأ شغلك؟" },
  { id: "N219", mode: "NUMBER", family: "music-media", text: "من آخر 5 أيام، كم يوم شفت فيلم أو حلقة قديمة تعرفها من قبل؟" },
  { id: "N220", mode: "NUMBER", family: "music-media", text: "من 0 إلى 5، قد إيش تحب تعيد أفلام أو مسلسلات؟" },
  { id: "N221", mode: "NUMBER", family: "music-media", text: "من آخر 5 أيام، كم يوم سمعت ألبوم أو قائمة أغاني كاملة؟" },
  { id: "N222", mode: "NUMBER", family: "music-media", text: "من 0 إلى 5، قد إيش تحب الوثائقيات؟" },
  { id: "N223", mode: "NUMBER", family: "music-media", text: "من آخر 5 أيام، كم يوم شفت تريلر قبل تختار وش تشوف؟" },
  { id: "N224", mode: "NUMBER", family: "music-media", text: "من 0 إلى 5، قد إيش تقدر توقف مسلسل ما عاد يعجبك؟" },
  { id: "N225", mode: "NUMBER", family: "sports-games", text: "من آخر 5 أيام، كم يوم لعبت لعبة جماعية؟" },
  { id: "N226", mode: "NUMBER", family: "sports-games", text: "من 0 إلى 5، قد إيش تحب ألعاب الألغاز؟" },
  { id: "N227", mode: "NUMBER", family: "sports-games", text: "من آخر 5 أيام، كم يوم شفت ملخص أو إعادة لقطة رياضية؟" },
  { id: "N228", mode: "NUMBER", family: "sports-games", text: "من 0 إلى 5، قد إيش تفضل الألعاب التعاونية على الفردية؟" },
  { id: "N229", mode: "NUMBER", family: "music-media", text: "من آخر 5 أيام، كم يوم حفظت أغنية جديدة أو جزء منها؟" },
  { id: "N230", mode: "NUMBER", family: "music-media", text: "من 0 إلى 5، قد إيش تحب المقاطع الطويلة إذا موضوعها يعجبك؟" },
];
