import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_NUMBER_6_PROMPTS: ImitationPrompt[] = [
  { id: "N261", mode: "NUMBER", family: "personality-decisions", text: "من آخر 5 أيام، كم يوم سألت شخص عن رأيه قبل قرار؟" },
  { id: "N262", mode: "NUMBER", family: "personality-decisions", text: "من 0 إلى 5، قد إيش تقبل تدفع أكثر مقابل جودة أفضل؟" },
  { id: "N263", mode: "NUMBER", family: "personality-decisions", text: "من آخر 5 أيام، كم يوم غيرت رأيك بعد ما سمعت سبب مقنع؟" },
  { id: "N264", mode: "NUMBER", family: "personality-decisions", text: "من 0 إلى 5، قد إيش تحب تتعلم بالتجربة أكثر من القراءة؟" },
  { id: "N265", mode: "NUMBER", family: "personality-decisions", text: "من آخر 5 أيام، كم يوم حاولت مرة ثانية بعد ما ما ضبطت أول مرة؟" },
  { id: "N266", mode: "NUMBER", family: "personality-decisions", text: "من 0 إلى 5، قد إيش تتجاوز الأخطاء الصغيرة بسرعة؟" },
  { id: "N267", mode: "NUMBER", family: "personality-decisions", text: "من آخر 5 أيام، كم يوم قسمت مهمة كبيرة لأجزاء أصغر؟" },
  { id: "N268", mode: "NUMBER", family: "personality-decisions", text: "من 0 إلى 5، قد إيش تفضل تركز على شي واحد كل مرة؟" },
  { id: "N269", mode: "NUMBER", family: "personality-decisions", text: "من آخر 5 أيام، كم يوم طلبت مساعدة بدل تضيع وقت طويل لحالك؟" },
  { id: "N270", mode: "NUMBER", family: "personality-decisions", text: "من 0 إلى 5، قد إيش تثق بأول إحساس لك بالاختيارات البسيطة؟" },
  { id: "N271", mode: "NUMBER", family: "personality-decisions", text: "من آخر 5 أيام، كم يوم اخترت مكان معروف لأنك كنت مستعجل؟" },
  { id: "N272", mode: "NUMBER", family: "personality-decisions", text: "من 0 إلى 5، قد إيش تحب تغير روتينك من فترة لفترة؟" },
  { id: "N273", mode: "NUMBER", family: "personality-decisions", text: "من آخر 5 أيام، كم يوم سألت سؤال مباشرة لما ما فهمت شي؟" },
  { id: "N274", mode: "NUMBER", family: "personality-decisions", text: "من 0 إلى 5، قد إيش تحب يكون عندك أكثر من خيار للخطة؟" },
  { id: "N275", mode: "NUMBER", family: "personality-decisions", text: "من آخر 5 أيام، كم يوم كافأت نفسك بعد إنجاز شي؟" },
  { id: "N276", mode: "NUMBER", family: "personality-decisions", text: "من 0 إلى 5، قد إيش تحب الأشياء اللي ما تحتاج تجهيز كثير؟" },
  { id: "N277", mode: "NUMBER", family: "personality-decisions", text: "من آخر 5 أيام، كم يوم حليت مشكلة صغيرة بنفسك؟" },
  { id: "N278", mode: "NUMBER", family: "personality-decisions", text: "من 0 إلى 5، قد إيش تغير رأيك بسهولة إذا ظهرت معلومة جديدة؟" },
  { id: "N279", mode: "NUMBER", family: "personality-decisions", text: "من آخر 5 أيام، كم يوم سويت قرار بسرعة وارتحت له؟" },
  { id: "N280", mode: "NUMBER", family: "personality-decisions", text: "من 0 إلى 5، قد إيش يهمك تنهي الخلاف قبل نهاية اليوم؟" },
  { id: "N281", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم جلست مع واحد من أهلك أكثر من نص ساعة؟" },
  { id: "N282", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تحب العزايم البيتية؟" },
  { id: "N283", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم ساعدت في تجهيز أو ترتيب سفرة؟" },
  { id: "N284", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تستمتع بسوالف كبار العائلة؟" },
  { id: "N285", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم اتصلت أو أرسلت لأحد من أهلك عشان تطمن عليه؟" },
  { id: "N286", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تحب تتعلم وصفة من شخص بالعائلة؟" },
  { id: "N287", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم جلست مع طفل ولعبت أو سولفت معه؟" },
  { id: "N288", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تحب توصل بدري للمناسبات العائلية؟" },
  { id: "N289", mode: "NUMBER", family: "social-gatherings", text: "من آخر 5 أيام، كم يوم شفت صورة عائلية قديمة؟" },
  { id: "N290", mode: "NUMBER", family: "social-gatherings", text: "من 0 إلى 5، قد إيش تتذكر مناسبات المقربين بدون تنبيه؟" },
];
