import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_POINT_3_PROMPTS: ImitationPrompt[] = [
  { id: "P166", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو الجو تغيّر فجأة بيكون غالبًا مجهز شي احتياط." },
  { id: "P167", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو رحلتكم فيها مشي كثير بيتحمس أكثر من غيره." },
  { id: "P168", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو سافرتوا بدون سيارة بيعرف يتعامل مع المواصلات أسرع." },
  { id: "P169", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو وصلتوا بدري للمطار يعرف كيف يقتل الوقت بدون ملل." },
  { id: "P170", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو تأخرت الرحلة بيقدر يحافظ على مزاجه." },
  { id: "P171", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو عندكم اختيار بين طريق أسرع وطريق أجمل ممكن يختار الأجمل." },
  { id: "P172", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو ضعتوا بمكان جديد بيبدأ يسأل الناس بدل يلف كثير." },
  { id: "P173", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو الجو ممتاز بيقترح طلعة خارجية بدل مكان مقفل." },
  { id: "P174", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو جتكم فرصة رحلة قصيرة نهاية الأسبوع بيجهز بسرعة." },
  { id: "P175", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو سافر مكان بارد غالبًا بيكون جايب ملابس زيادة." },
  { id: "P176", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو المشوار ساعتين بيعرف يختار وش تسمعون بالطريق." },
  { id: "P177", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو دخلتم حي ما تعرفونه بيلاحظ الأماكن اللي تستاهل ترجعون لها." },
  { id: "P178", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو وصلتوا وجهتكم قبل الموعد بيقترح شي قريب تسوونه." },
  { id: "P179", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو الرحلة فيها جدول مزدحم بيطلب وقت راحة قبل ما يتعب الكل." },
  { id: "P180", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو ما فيه مواقف قريبة بيقبل يمشي مسافة بدل يلف كثير." },
  { id: "P181", mode: "POINT", family: "planning-time", text: "أشر على اللي لو أحد تأخر على الموعد بيكون أكثر واحد متفهم." },
  { id: "P182", mode: "POINT", family: "planning-time", text: "أشر على اللي لو عندكم ثلاث مشاوير بيعرف يرتبها بطريقة توفر وقت." },
  { id: "P183", mode: "POINT", family: "planning-time", text: "أشر على اللي لو اتغير الموعد مرتين يظل متابع وما يلخبط." },
  { id: "P184", mode: "POINT", family: "planning-time", text: "أشر على اللي لو قلتوا التجمع الساعة 7 بيعتبر 7 وقت وصول مو وقت خروج من البيت." },
  { id: "P185", mode: "POINT", family: "planning-time", text: "أشر على اللي لو عنده يوم مزدحم يحط وقت احتياط بين الأشياء." },
  { id: "P186", mode: "POINT", family: "planning-time", text: "أشر على اللي لو صار عندكم قرار لازم ينحسم اليوم بيقدر يختار بدون تدوير كثير." },
  { id: "P187", mode: "POINT", family: "planning-time", text: "أشر على اللي لو الخطة مو واضحة بيسأل عن التفاصيل المهمة أول." },
  { id: "P188", mode: "POINT", family: "planning-time", text: "أشر على اللي لو عندكم مشروع جماعي بيقسم المهام بطريقة واضحة." },
  { id: "P189", mode: "POINT", family: "planning-time", text: "أشر على اللي لو نسي موعد مرة غالبًا بعدها يصير أدق فترة." },
  { id: "P190", mode: "POINT", family: "planning-time", text: "أشر على اللي لو عنده شي مهم بكرة يجهز أغراضه من الليلة." },
  { id: "P191", mode: "POINT", family: "planning-time", text: "أشر على اللي لو اتفقتوا على مكان ثم صار بعيد على واحد منكم بيدور حل وسط." },
  { id: "P192", mode: "POINT", family: "planning-time", text: "أشر على اللي لو تأخرتوا في الخروج بيعيد ترتيب الخطة بدل يلغي كل شي." },
  { id: "P193", mode: "POINT", family: "planning-time", text: "أشر على اللي لو عنده خيار موعد صباح أو مساء بيعرف وش يناسب يومه بسرعة." },
  { id: "P194", mode: "POINT", family: "planning-time", text: "أشر على اللي لو قلتوا «بنقرر بعدين» بيرجع يفتح الموضوع قبل يفوت الوقت." },
  { id: "P195", mode: "POINT", family: "planning-time", text: "أشر على اللي لو الخطة فيها أكثر من خطوة يتذكر الترتيب بدون ما أحد يذكره." },
];
