import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_POINT_1_PROMPTS: ImitationPrompt[] = [
  { id: "P101", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو انطفى جواله بنص الطلعة بيكمل يومه عادي بدون توتر." },
  { id: "P102", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو القروب هادي يوم كامل غالبًا بيرسل شي يفتح السالفة." },
  { id: "P103", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو أحد أرسل موقع غلط بيلاحظ قبل ما تتحركون كثير." },
  { id: "P104", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو جاته رسالة طويلة بيرد عليها بنقاط مرتبة." },
  { id: "P105", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو ضاع منه شي بالجوال بيعرف يستخدم البحث ويوصله بسرعة." },
  { id: "P106", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو نزل تحديث جديد للتطبيق بيجرب الميزة الجديدة أول." },
  { id: "P107", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو صار عنده 1٪ بطارية بيحافظ عليها لأهم شي بدل يقفل الجوال." },
  { id: "P108", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو وصلته مكالمة وقت القعدة بيطلع يرد بعيد عن الناس." },
  { id: "P109", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو طلبت منه صورة قديمة بيرسلها ومعها قصة كاملة." },
  { id: "P110", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو أحد أرسل له رابط طويل غالبًا يفتحه الحين مو بعدين." },
  { id: "P111", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو سوّيتوا قروب جديد بيرتب الاسم والصورة أول." },
  { id: "P112", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو نسى كلمة سر بيتعامل مع الموضوع بهدوء أكثر." },
  { id: "P113", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو انرسلت رسالة بالغلط بالقروب بيعرف يتصرف أسرع." },
  { id: "P114", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو تعطلت سماعاته بيكمل المشوار بدون ما يشتري غيرها فورًا." },
  { id: "P115", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو شاف إشعار مهم وهو مشغول بيتذكر يرجع له بعدين." },
  { id: "P116", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو أرسل فويس طويل بيختصر لك زبدته إذا سألته." },
  { id: "P117", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو احتاج يشرح موقع بيتهم بيعطيك وصف أوضح من الباقين." },
  { id: "P118", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو صورتم صورة جماعية بينتبه لو أحد ما طلع بالصورة." },
  { id: "P119", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو القروب صار فيه نقاش طويل بيقرأ كل الكلام قبل يرد." },
  { id: "P120", mode: "POINT", family: "phone-messaging", text: "أشر على اللي لو صار النت بطيء بيطلع له حل ثاني بدل يعيد التحميل عشر مرات." },
  { id: "P121", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو عندكم موعد بدري بيكون مزاجه أحسن واحد من الصباح." },
  { id: "P122", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو السهرة طولت بيظل صاحي ومركز أكثر." },
  { id: "P123", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو نام أقل من المعتاد بيقدر يكمل يومه بدون ما يبين عليه كثير." },
  { id: "P124", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو عندكم مشوار بعد الفجر بيكون أول واحد متقبل الفكرة." },
  { id: "P125", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو صار عنده ساعة فاضية فجأة ممكن يستغلها بنومة." },
  { id: "P126", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو شرب قهوة بالليل غالبًا ما تأثر على نومه كثير." },
  { id: "P127", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو صحيتوه من النوم بيعرف وش السالفة بسرعة." },
  { id: "P128", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو نام بمكان جديد بيتأقلم أسرع." },
  { id: "P129", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو عندكم يوم طويل من الصباح بيحافظ على طاقته للنهاية." },
  { id: "P130", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو الجلسة هادية آخر الليل ممكن ينعس قبل الباقين." },
  { id: "P131", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو نسى يحط منبّه غالبًا يصحى قريب من وقته." },
  { id: "P132", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو عنده يوم فاضي بيحب يبدأه بدري بدل ينام للظهر." },
  { id: "P133", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو سهر يومين ورا بعض بيقرر يعوض نومه بسرعة." },
  { id: "P134", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو قعد من النوم بدري بالغلط ممكن يستغل الصباح بدل يرجع ينام." },
  { id: "P135", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو الكل تعبان بيكون عنده طاقة يكمل مشوار إضافي." },
];
