import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_NUMBER_1_PROMPTS: ImitationPrompt[] = [
  { id: "N101", mode: "NUMBER", family: "phone-messaging", text: "من آخر 5 أيام، كم يوم استخدمت وضع عدم الإزعاج بجوالك؟" },
  { id: "N102", mode: "NUMBER", family: "phone-messaging", text: "من 0 إلى 5، قد إيش يضايقك يكون عندك إشعارات كثيرة؟" },
  { id: "N103", mode: "NUMBER", family: "phone-messaging", text: "من آخر 5 أيام، كم يوم كتبت شي بالملاحظات عشان ما تنساه؟" },
  { id: "N104", mode: "NUMBER", family: "phone-messaging", text: "من 0 إلى 5، قد إيش تفضّل الرسائل النصية على الفويسات؟" },
  { id: "N105", mode: "NUMBER", family: "phone-messaging", text: "من آخر 5 أيام، كم يوم شاركت موقعك مع أحد؟" },
  { id: "N106", mode: "NUMBER", family: "phone-messaging", text: "من 0 إلى 5، قد إيش تهتم يكون شحن جوالك عالي قبل تطلع؟" },
  { id: "N107", mode: "NUMBER", family: "phone-messaging", text: "من آخر 5 أيام، كم يوم فتحت محادثة قديمة تدور معلومة؟" },
  { id: "N108", mode: "NUMBER", family: "phone-messaging", text: "من 0 إلى 5، قد إيش تحب ترتب تطبيقات جوالك؟" },
  { id: "N109", mode: "NUMBER", family: "phone-messaging", text: "من آخر 5 أيام، كم يوم صورت لقطة شاشة لشي مهم؟" },
  { id: "N110", mode: "NUMBER", family: "phone-messaging", text: "من 0 إلى 5، قد إيش تتقبل تقعد ساعة بدون إنترنت؟" },
  { id: "N111", mode: "NUMBER", family: "phone-messaging", text: "من آخر 5 أيام، كم يوم استخدمت التقويم أو التذكيرات؟" },
  { id: "N112", mode: "NUMBER", family: "phone-messaging", text: "من 0 إلى 5، قد إيش تراجع رسالتك قبل ترسلها؟" },
  { id: "N113", mode: "NUMBER", family: "phone-messaging", text: "من آخر 5 أيام، كم يوم اتصلت بأحد بدل ما ترسل له؟" },
  { id: "N114", mode: "NUMBER", family: "phone-messaging", text: "من 0 إلى 5، قد إيش تحب تشوف إشعاراتك أول بأول؟" },
  { id: "N115", mode: "NUMBER", family: "phone-messaging", text: "من آخر 5 أيام، كم يوم استخدمت شاحن متنقل؟" },
  { id: "N116", mode: "NUMBER", family: "phone-messaging", text: "من 0 إلى 5، قد إيش تتوتر إذا بطارية جوالك قربت تخلص؟" },
  { id: "N117", mode: "NUMBER", family: "phone-messaging", text: "من آخر 5 أيام، كم يوم أرسلت صورة أو فيديو لقروب؟" },
  { id: "N118", mode: "NUMBER", family: "phone-messaging", text: "من 0 إلى 5، قد إيش تستخدم البحث داخل التطبيقات بدل التصفح؟" },
  { id: "N119", mode: "NUMBER", family: "phone-messaging", text: "من آخر 5 أيام، كم يوم خليت جوالك على الصامت أغلب اليوم؟" },
  { id: "N120", mode: "NUMBER", family: "phone-messaging", text: "من 0 إلى 5، قد إيش تحب تقلل وقتك على الجوال إذا قدرت؟" },
  { id: "N121", mode: "NUMBER", family: "sleep-energy", text: "من آخر 5 أيام، كم يوم صحيت قبل المنبّه؟" },
  { id: "N122", mode: "NUMBER", family: "sleep-energy", text: "من 0 إلى 5، قد إيش تحتاج وقت عشان تصحصح بعد ما تقوم؟" },
  { id: "N123", mode: "NUMBER", family: "sleep-energy", text: "من آخر 5 أيام، كم يوم رتبت سريرك أول ما صحيت؟" },
  { id: "N124", mode: "NUMBER", family: "sleep-energy", text: "من 0 إلى 5، قد إيش تفضّل الغرفة الباردة للنوم؟" },
  { id: "N125", mode: "NUMBER", family: "sleep-energy", text: "من آخر 5 أيام، كم يوم أخذت لك وقت هادي بدون شاشة قبل النوم؟" },
  { id: "N126", mode: "NUMBER", family: "sleep-energy", text: "من 0 إلى 5، قد إيش تقدر تنام بمكان مو بيتك؟" },
  { id: "N127", mode: "NUMBER", family: "sleep-energy", text: "من آخر 5 أيام، كم يوم شربت موية أول ما صحيت؟" },
  { id: "N128", mode: "NUMBER", family: "sleep-energy", text: "من 0 إلى 5، قد إيش تحب تصحى بدري بالإجازة؟" },
  { id: "N129", mode: "NUMBER", family: "sleep-energy", text: "من آخر 5 أيام، كم يوم نمت أكثر من اللي كنت مخطط له؟" },
  { id: "N130", mode: "NUMBER", family: "sleep-energy", text: "من 0 إلى 5، قد إيش يفرق معك يكون المكان مظلم تمامًا وقت النوم؟" },
  { id: "N131", mode: "NUMBER", family: "sleep-energy", text: "من آخر 5 أيام، كم يوم حسيت إنك احتجت قيلولة وما أخذتها؟" },
  { id: "N132", mode: "NUMBER", family: "sleep-energy", text: "من 0 إلى 5، قد إيش تركيزك يكون أفضل بالليل؟" },
  { id: "N133", mode: "NUMBER", family: "sleep-energy", text: "من آخر 5 أيام، كم يوم بدأت يومك بدون استعجال؟" },
  { id: "N134", mode: "NUMBER", family: "sleep-energy", text: "من 0 إلى 5، قد إيش تحب يكون نومك بنفس الوقت كل يوم؟" },
  { id: "N135", mode: "NUMBER", family: "sleep-energy", text: "من آخر 5 أيام، كم يوم جلست صاحي بعد ما قلت لنفسك «بنام الحين»؟" },
];
