import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_POINT_2_PROMPTS: ImitationPrompt[] = [
  { id: "P136", mode: "POINT", family: "sleep-energy", text: "أشر على اللي لو صار الصبح بارد بيطلع من السرير أسرع من غيره." },
  { id: "P137", mode: "POINT", family: "food-drink", text: "أشر على اللي لو طلبتوا فطور جماعي بيقترح شي غير المعتاد." },
  { id: "P138", mode: "POINT", family: "food-drink", text: "أشر على اللي لو المنيو فيه أطباق كثيرة بيختار شي ما جربه من قبل." },
  { id: "P139", mode: "POINT", family: "food-drink", text: "أشر على اللي لو الطبق طلع حار مرة بيكمله بدون مشكلة." },
  { id: "P140", mode: "POINT", family: "food-drink", text: "أشر على اللي لو طلبكم تأخر بيفضل ينتظر بدل يغير المطعم." },
  { id: "P141", mode: "POINT", family: "food-drink", text: "أشر على اللي لو عندكم حلا واحد بالنص غالبًا يكتفي بأقل قطعة." },
  { id: "P142", mode: "POINT", family: "food-drink", text: "أشر على اللي لو الكل محتار بين قهوة وشاهي بيختار بسرعة." },
  { id: "P143", mode: "POINT", family: "food-drink", text: "أشر على اللي لو مطعم جديد فتح قريب بيدخل يشوف المنيو حتى لو مو جوعان." },
  { id: "P144", mode: "POINT", family: "food-drink", text: "أشر على اللي لو طبختوا سوا بيتحمس يجرب خطوة ما يعرفها." },
  { id: "P145", mode: "POINT", family: "food-drink", text: "أشر على اللي لو الأكل طلع أقل من المتوقع بيعرف يقسمه بينكم بعدل." },
  { id: "P146", mode: "POINT", family: "food-drink", text: "أشر على اللي لو في الأكل مكوّن ما يحبه بيقدر يتجاوزه بدون ما يغير الطلب." },
  { id: "P147", mode: "POINT", family: "food-drink", text: "أشر على اللي لو أحد طلب رأيه بأكلة بيعطي وصف دقيق مو بس «زين»." },
  { id: "P148", mode: "POINT", family: "food-drink", text: "أشر على اللي لو رحتوا بوفيه بيختار أصناف قليلة ويكملها." },
  { id: "P149", mode: "POINT", family: "food-drink", text: "أشر على اللي لو عندكم قهوة مختصة بيلاحظ فرق النكهة أكثر." },
  { id: "P150", mode: "POINT", family: "food-drink", text: "أشر على اللي لو خيّرتوه بين مطعم فاخر وأكلة شعبية ممتازة ممكن يختار الشعبية." },
  { id: "P151", mode: "POINT", family: "food-drink", text: "أشر على اللي لو طلبتم أكل كثير بيحرص ما يروح الباقي هدر." },
  { id: "P152", mode: "POINT", family: "food-drink", text: "أشر على اللي لو جبتوا أكلة غريبة للجَمعة بيكون أول واحد يسأل وش فيها." },
  { id: "P153", mode: "POINT", family: "food-drink", text: "أشر على اللي لو المشروب طلع حلو زيادة بيكمله عادي." },
  { id: "P154", mode: "POINT", family: "food-drink", text: "أشر على اللي لو دخل مطعم يعرفه يقدر يختار بدون ما يفتح المنيو." },
  { id: "P155", mode: "POINT", family: "food-drink", text: "أشر على اللي لو كل واحد بيجيب طبق للجَمعة بتتوقع منه شي مرتب." },
  { id: "P156", mode: "POINT", family: "food-drink", text: "أشر على اللي لو أحد قال «خلونا نطبخ بدل نطلب» بيوافق أسرع." },
  { id: "P157", mode: "POINT", family: "food-drink", text: "أشر على اللي لو القهوة بردت يشربها بدل يسوي غيرها." },
  { id: "P158", mode: "POINT", family: "food-drink", text: "أشر على اللي لو عندكم خيار توصيل أو استلام بنفسكم ممكن يختار يروح يستلم." },
  { id: "P159", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو وصل مدينة جديدة بيدور مكان فطور محلي بدل سلسلة معروفة." },
  { id: "P160", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو الطريق طويل بيقترح وقفة مناسبة قبل لا أحد يطلب." },
  { id: "P161", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو ضيعتوا مخرج بالسيارة بيظل أهدى واحد." },
  { id: "P162", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو الرحلة فيها تغيير خطة مفاجئ بيتأقلم أسرع." },
  { id: "P163", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو الفندق ما كان مثل الصور بيعرف يتعامل مع الموضوع بدون ما يخرب مزاجه." },
  { id: "P164", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو عندكم يوم واحد بمدينة كبيرة بيعرف يختار أهم شي تسوونه." },
  { id: "P165", mode: "POINT", family: "travel-driving", text: "أشر على اللي لو الطريق فيه منظر حلو بيطلب توقفون دقيقة." },
];
