import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_HANDS_A_PROMPTS: ImitationPrompt[] = [
  { id: "H101", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تقفل إشعارات بعض القروبات عشان ترتاح." },
  { id: "H102", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا ترد على الرسالة في بالك وتنسى تكتب الرد فعلًا." },
  { id: "H103", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا عندك محادثة مثبتة فوق من زمان." },
  { id: "H104", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تفتح الكاميرا بالغلط وأنت تقصد تطبيق ثاني." },
  { id: "H105", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تغيّر خلفية جوالك أكثر من مرة بالسنة." },
  { id: "H106", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تقفل الواي فاي وتفتحه كأن المشكلة بتنحل لحالها." },
  { id: "H107", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تحفظ رقم أحد باسم غريب عشان تتذكره." },
  { id: "H108", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا ترسل لنفسك أشياء عشان ترجع لها بعدين." },
  { id: "H109", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا عندك تبويبات كثيرة مفتوحة بالمتصفح وما تقفلها." },
  { id: "H110", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تسوي لقطة شاشة لتذكرة أو موقع قبل ما تطلع." },
  { id: "H111", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تحذف تطبيق وترجعه بعد فترة قصيرة." },
  { id: "H112", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تكتب ملاحظة بالجوال بدل ما تعتمد على ذاكرتك." },
  { id: "H113", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا عندك قروب تقراه أكثر مما تكتب فيه." },
  { id: "H114", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تستخدم البحث داخل المحادثة عشان تلقى معلومة قديمة." },
  { id: "H115", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تطفي صوت مقطع قبل ما تفتحه بمكان عام." },
  { id: "H116", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا ترسل موقعك لأحد بدل ما تشرح له الطريق." },
  { id: "H117", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تتأكد من اسم الشخص قبل ما ترسل له صورة أو رسالة." },
  { id: "H118", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تستخدم وضع عدم الإزعاج وقت النوم." },
  { id: "H119", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا تغيّر نغمة المنبّه لأنك صرت تكره القديمة." },
  { id: "H120", mode: "HANDS", family: "phone-messaging", text: "ارفع يدك إذا ترجع تقرأ رسالتك بعد ما ترسلها." },
  { id: "H121", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تقوم من السرير أول ما يرن المنبّه بدون تفاوض." },
  { id: "H122", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا أول شي تسويه بعد ما تصحى تفتح الستارة." },
  { id: "H123", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تحتاج هدوء شوي قبل ما تبدأ يومك." },
  { id: "H124", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تنام أسرع إذا الغرفة باردة." },
  { id: "H125", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تقدر تنام بأي مكان وقت السفر." },
  { id: "H126", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا صحيت بدري بالإجازة تعتبرها فرصة مو خسارة." },
  { id: "H127", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تحب ترتب سريرك أول ما تقوم." },
  { id: "H128", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تاخذ وقت طويل عشان تنام حتى لو كنت تعبان." },
  { id: "H129", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تحب تشرب موية أول ما تصحى." },
  { id: "H130", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تنام أفضل والباب مقفل." },
  { id: "H131", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تحتاج منبّه واحد قوي بدل عدة منبهات." },
  { id: "H132", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا ما تعرف تنام إذا فيه لمبة صغيرة شغالة." },
  { id: "H133", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تحب تبدأ شغلك أو دراستك بدري وتخلص." },
  { id: "H134", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تركّز أكثر بالليل من الصباح." },
  { id: "H135", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا وقت الإجازة يتغير نومك بسرعة." },
  { id: "H136", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تحب تاخذ لك عشر دقايق هدوء بعد يوم طويل." },
  { id: "H137", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تقوم تشرب موية بنص الليل." },
  { id: "H138", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا نمت قيلولة تحط لها منبّه." },
  { id: "H139", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا تحب الويكند يبدأ بصباح هادي." },
  { id: "H140", mode: "HANDS", family: "sleep-energy", text: "ارفع يدك إذا صحيت قبل موعدك بنص ساعة ما ترجع تنام." },
  { id: "H141", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تذوق أكلة جديدة قبل ما تسأل وش مكوناتها." },
  { id: "H142", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تحب الصوصات تكون على جنب مو فوق الأكل." },
  { id: "H143", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تاكل البطاطس قبل الساندويتش." },
  { id: "H144", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تفضّل الفطور المالح على الحلو." },
  { id: "H145", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تطلب مشروبك بدون ثلج غالبًا." },
  { id: "H146", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تحب تجرب قهوة من مكان جديد." },
  { id: "H147", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا عندك وجبة تقدر تكررها أكثر من مرة بالأسبوع." },
  { id: "H148", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تحب تقسم الحلا مع أحد بدل تطلب واحد كامل." },
  { id: "H149", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تقرأ المنيو كامل حتى لو تعرف وش بتطلب." },
  { id: "H150", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تفضّل الأكل الحار وهو طالع توه من المطبخ." },
  { id: "H151", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا جعت بالليل تفتح المطبخ وتسوّي شي بنفسك." },
  { id: "H152", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تحب الليمون على أكلات كثيرة." },
  { id: "H153", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا ما تحب تخلط أشياء كثيرة في نفس الصحن." },
  { id: "H154", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا أول شي تشوفه بالمطعم تقييم الناس قبل المنيو." },
  { id: "H155", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تفضّل القهوة بدون سكر." },
  { id: "H156", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تحب الشاهي خفيف." },
  { id: "H157", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا الأكل طلع كثير تحرص تاخذه معك بدل يروح." },
  { id: "H158", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تحب الفشار مالح أكثر من حلو." },
  { id: "H159", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تختار العصير الطبيعي إذا كان موجود." },
  { id: "H160", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تقدر تأكل نفس الأكلة يومين ورا بعض." },
  { id: "H161", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تحب تطبخ شي بسيط للناس اللي معك." },
  { id: "H162", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تحب تجرب بهارات جديدة بالبيت." },
  { id: "H163", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تفضّل تطلب مقبلات وتشاركها مع الكل." },
  { id: "H164", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا تحب القهوة بعد الأكل أكثر من قبل الأكل." },
  { id: "H165", mode: "HANDS", family: "food-drink", text: "ارفع يدك إذا شفت مخبز جديد توقف تشوف وش عنده." },
  { id: "H166", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا تجهز أغراضك للسفر بقائمة." },
  { id: "H167", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا تحب تكون بالمطار قبل الرحلة بوقت مريح." },
  { id: "H168", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا سافرت تحب تمشي بالحي بدون خطة." },
  { id: "H169", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا تختار المقعد القريب من الممر أكثر من الشباك." },
  { id: "H170", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا تحب الرحلات اللي فيها أكثر من مدينة." },
  { id: "H171", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا تصور اسم موقف السيارة عشان ما تنساه." },
  { id: "H172", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا تراجع الطقس قبل أي طلعة طويلة." },
  { id: "H173", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا تحمل معك شاحن متنقل بأي سفر." },
  { id: "H174", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا تحب توقف بالطريق لمكان عشوائي شكله حلو." },
  { id: "H175", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا تفضّل تبدأ مشوار السفر الصباح على الليل." },
  { id: "H176", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا الطريق جديد تتابع اللوحات حتى والخرائط شغالة." },
  { id: "H177", mode: "HANDS", family: "travel-driving", text: "ارفع يدك إذا تحب تجلس برا إذا الجو معتدل." },
  { id: "H178", mode: "HANDS", family: "weather-outdoors", text: "ارفع يدك إذا تفضّل الشتاء لأن الطلعات فيه أريح لك." },
  { id: "H179", mode: "HANDS", family: "weather-outdoors", text: "ارفع يدك إذا شفت غروب حلو توقف تتفرج شوي." },
  { id: "H180", mode: "HANDS", family: "weather-outdoors", text: "ارفع يدك إذا تحب المشي في مكان مفتوح أكثر من المول." },
  { id: "H181", mode: "HANDS", family: "weather-outdoors", text: "ارفع يدك إذا تأخذ معك جاكيت احتياط حتى لو الجو مو بارد مرة." },
  { id: "H182", mode: "HANDS", family: "weather-outdoors", text: "ارفع يدك إذا تحب القعدة في الحوش أو السطح وقت الجو الحلو." },
  { id: "H183", mode: "HANDS", family: "weather-outdoors", text: "ارفع يدك إذا صار الجو غبار تفضّل تلغي الطلعة." },
  { id: "H184", mode: "HANDS", family: "weather-outdoors", text: "ارفع يدك إذا تحب طريق السفر نفسه قد الوجهة." },
  { id: "H185", mode: "HANDS", family: "weather-outdoors", text: "ارفع يدك إذا تفضّل الرحلة القصيرة المتكررة على سفرة طويلة نادرة." },
  { id: "H186", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تحب تكون الشخص اللي يجمع الناس على موعد." },
  { id: "H187", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تسأل عن الوقت قبل ما توافق على أي طلعة." },
  { id: "H188", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تفضّل الخطة الواضحة على «نشوف وش يصير»." },
  { id: "H189", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تأخرت تحب تبلغ الناس بدري." },
  { id: "H190", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تحط مواعيدك في التقويم." },
  { id: "H191", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا عندك أكثر من مشوار ترتبهم حسب المكان." },
  { id: "H192", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تحب توصل قبل الموعد بخمس دقايق." },
  { id: "H193", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تفضّل تحدد المطعم قبل ما تطلع من البيت." },
  { id: "H194", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تغيرت الخطة فجأة تحتاج دقيقة ترتب نفسك." },
  { id: "H195", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تكتب الأشياء المهمة عشان ما تعتمد على ذاكرتك." },
];
