import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_NUMBER_2_PROMPTS: ImitationPrompt[] = [
  { id: "N136", mode: "NUMBER", family: "sleep-energy", text: "من 0 إلى 5، قد إيش تتأثر إذا نقص نومك ساعة؟" },
  { id: "N137", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم أكلت فطور مالح؟" },
  { id: "N138", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش تحب الصوص يكون على جنب؟" },
  { id: "N139", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم شربت قهوتك بدون سكر؟" },
  { id: "N140", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش تحب تجرب نكهة جديدة بمشروبك؟" },
  { id: "N141", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم أكلت شي حار؟" },
  { id: "N142", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش تفضّل الفطور على العشاء كنوع أكل؟" },
  { id: "N143", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم طبخت أو حضرت أكلك بنفسك؟" },
  { id: "N144", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش تحب تشارك المقبلات مع الكل؟" },
  { id: "N145", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم أكلت فاكهة؟" },
  { id: "N146", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش يهمك تقييم المطعم قبل تجربه؟" },
  { id: "N147", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم أخذت أكلك الباقي معك بدل تتركه؟" },
  { id: "N148", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش تحب الليمون مع الأكل؟" },
  { id: "N149", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم شربت عصير طبيعي؟" },
  { id: "N150", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش تقدر تكرر نفس الوجبة بدون تمل؟" },
  { id: "N151", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم جربت شي بالأكل مو من اختيارك المعتاد؟" },
  { id: "N152", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش تحب القهوة بعد الوجبة؟" },
  { id: "N153", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم أكلت سناك بين الوجبات؟" },
  { id: "N154", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش تحب الفشار المالح؟" },
  { id: "N155", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم جلست على سفرة مع ناس بدل تاكل لحالك؟" },
  { id: "N156", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش تفضل الأكل البيتي على المطاعم؟" },
  { id: "N157", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم شربت شاهي بعد الأكل؟" },
  { id: "N158", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش تحب تجرب مخبز أو محل حلا جديد؟" },
  { id: "N159", mode: "NUMBER", family: "food-drink", text: "من آخر 5 أيام، كم يوم اخترت وجبة خفيفة بدل وجبة كبيرة؟" },
  { id: "N160", mode: "NUMBER", family: "food-drink", text: "من 0 إلى 5، قد إيش تحب تختار الطلب بسرعة بدون ما تقرأ المنيو كله؟" },
  { id: "N161", mode: "NUMBER", family: "travel-driving", text: "من آخر 5 أيام، كم يوم طلعت لمشوار بطريق ما تستخدمه عادة؟" },
  { id: "N162", mode: "NUMBER", family: "travel-driving", text: "من 0 إلى 5، قد إيش تحب الجلسة جنب الممر وقت السفر؟" },
  { id: "N163", mode: "NUMBER", family: "travel-driving", text: "من آخر 5 أيام، كم يوم شيكت على الطقس قبل تطلع؟" },
  { id: "N164", mode: "NUMBER", family: "travel-driving", text: "من 0 إلى 5، قد إيش تستمتع بطريق السفر نفسه؟" },
  { id: "N165", mode: "NUMBER", family: "travel-driving", text: "من آخر 5 أيام، كم يوم مشيت بمكان مفتوح أكثر من 20 دقيقة؟" },
];
