import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_HANDS_B_PROMPTS: ImitationPrompt[] = [
  { id: "H196", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تفضّل تخلص الأشياء الثقيلة أول اليوم." },
  { id: "H197", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا عندك موعد مهم تجهز له من الليلة اللي قبل." },
  { id: "H198", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تحب تعرف كم بيطول المشوار قبل ما تبدأه." },
  { id: "H199", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تعطي نفسك وقت احتياط للزحمة." },
  { id: "H200", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا خلصت بدري من شي تبدأ اللي بعده بدل تنتظر." },
  { id: "H201", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تحب أيامك تكون مرنة بدون جدول دقيق." },
  { id: "H202", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا وعدت أحد بوقت تحرص تمسكه." },
  { id: "H203", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تراجع قائمة مهامك أكثر من مرة باليوم." },
  { id: "H204", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا عندك عادة تسويها بنفس الوقت تقريبًا كل يوم." },
  { id: "H205", mode: "HANDS", family: "planning-time", text: "ارفع يدك إذا تفضّل ترتب أسبوعك من بدايته." },
  { id: "H206", mode: "HANDS", family: "shopping-money", text: "ارفع يدك إذا تحب تكون آخر واحد يختار الهدية عشان تشوف اقتراحات الباقين." },
  { id: "H207", mode: "HANDS", family: "shopping-money", text: "ارفع يدك إذا تقارن السعر بين أكثر من متجر قبل شراء شي غالي." },
  { id: "H208", mode: "HANDS", family: "shopping-money", text: "ارفع يدك إذا تحب تشتري الأشياء العملية أكثر من الشكلية." },
  { id: "H209", mode: "HANDS", family: "shopping-money", text: "ارفع يدك إذا تحتفظ بالفاتورة لين تتأكد إنك ما تحتاج ترجع الشي." },
  { id: "H210", mode: "HANDS", family: "shopping-money", text: "ارفع يدك إذا تستنى التخفيض إذا الشي مو مستعجل." },
  { id: "H211", mode: "HANDS", family: "shopping-money", text: "ارفع يدك إذا تفضّل تشوف المنتج قدامك قبل تشتريه." },
  { id: "H212", mode: "HANDS", family: "shopping-money", text: "ارفع يدك إذا تحط ميزانية تقريبية للطلعة قبل تطلع." },
  { id: "H213", mode: "HANDS", family: "shopping-money", text: "ارفع يدك إذا أعجبك شي غالي تنتظر يوم قبل تقرر." },
  { id: "H214", mode: "HANDS", family: "shopping-money", text: "ارفع يدك إذا تحب تهدي شي يستخدمه الشخص فعلًا." },
  { id: "H215", mode: "HANDS", family: "shopping-money", text: "ارفع يدك إذا تدخل محل بدون نية شراء وتطلع فعلًا بدون شي." },
  { id: "H216", mode: "HANDS", family: "home-routine", text: "ارفع يدك إذا ترتب درج واحد إذا حسيت البيت ملخبط." },
  { id: "H217", mode: "HANDS", family: "home-routine", text: "ارفع يدك إذا عندك مكان ثابت للمفاتيح والمحفظة." },
  { id: "H218", mode: "HANDS", family: "home-routine", text: "ارفع يدك إذا تصلح الشي البسيط بنفسك قبل تفكر تبدله." },
  { id: "H219", mode: "HANDS", family: "home-routine", text: "ارفع يدك إذا تطوي الملابس أول ما تنشف." },
  { id: "H220", mode: "HANDS", family: "home-routine", text: "ارفع يدك إذا تحب سطح المكتب أو الطاولة تكون فاضية." },
  { id: "H221", mode: "HANDS", family: "home-routine", text: "ارفع يدك إذا ترجع الشي مكانه مباشرة بعد ما تستخدمه." },
  { id: "H222", mode: "HANDS", family: "home-routine", text: "ارفع يدك إذا عندك صندوق للأشياء اللي ما تعرف وين تحطها." },
  { id: "H223", mode: "HANDS", family: "home-routine", text: "ارفع يدك إذا تنظف وأنت تسمع شي." },
  { id: "H224", mode: "HANDS", family: "home-routine", text: "ارفع يدك إذا تحب تفتح الشبابيك وقت ترتيب البيت." },
  { id: "H225", mode: "HANDS", family: "home-routine", text: "ارفع يدك إذا قبل ما تطلع تتأكد من الغاز أو الأبواب مرة وحدة تكفيك." },
  { id: "H226", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تحب تعيد فيلم قديم تعرفه بدل تبدأ شي جديد." },
  { id: "H227", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تختار الفيلم على حسب الممثل أكثر من التقييم." },
  { id: "H228", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تقدر تسمع ألبوم كامل من أوله لآخره." },
  { id: "H229", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تحب المقاطع القصيرة أكثر من الفيديوهات الطويلة." },
  { id: "H230", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا توقف المسلسل إذا حسيت القصة مطّت." },
  { id: "H231", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تشوف التريلر قبل ما تبدأ فيلم." },
  { id: "H232", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تحفظ أغاني من أول كم مرة تسمعها." },
  { id: "H233", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا عندك بودكاست ترجع له باستمرار." },
  { id: "H234", mode: "HANDS", family: "sports-games", text: "ارفع يدك إذا تحب تشوف مباراة حتى لو الفريق اللي تشجعه مو موجود." },
  { id: "H235", mode: "HANDS", family: "sports-games", text: "ارفع يدك إذا لعبت لعبة جديدة تبدأ بالإعدادات قبل اللعب." },
  { id: "H236", mode: "HANDS", family: "sports-games", text: "ارفع يدك إذا تفضّل ألعاب الفريق على اللعب لحالك." },
  { id: "H237", mode: "HANDS", family: "sports-games", text: "ارفع يدك إذا تحب الألغاز اللي تحتاج وقت." },
  { id: "H238", mode: "HANDS", family: "sports-games", text: "ارفع يدك إذا خسرت لعبة تقول «جولة أخيرة» وتعيد." },
  { id: "H239", mode: "HANDS", family: "sports-games", text: "ارفع يدك إذا تقدر تتفرج على مباراة بدون تمسك جوالك." },
  { id: "H240", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تحب تسمع الموسيقى بالسماعات أكثر من السماعة الخارجية." },
  { id: "H241", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تختار شي خفيف تتفرج عليه بعد يوم طويل." },
  { id: "H242", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تحفظ اقتراحات أفلام في قائمة." },
  { id: "H243", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تحب الوثائقيات." },
  { id: "H244", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تفضّل تشوف الموسم كامل بعد ما ينزل بدل تنتظر كل حلقة." },
  { id: "H245", mode: "HANDS", family: "music-media", text: "ارفع يدك إذا تتذكر موسيقى فيلم أكثر من تفاصيل قصته." },
  { id: "H246", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا ترتاح أكثر في جمعة صغيرة من مناسبة كبيرة." },
  { id: "H247", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تبدأ السلام على الناس أول ما تدخل." },
  { id: "H248", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تحب تعرف الناس على بعض إذا أحد جديد بالجموعة." },
  { id: "H249", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تقدر تسولف مع شخص ما تعرفه بسهولة." },
  { id: "H250", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا أحد ساكت بالجَمعة تحاول تدخله بالسوالف." },
  { id: "H251", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تحب تسمع القصة كاملة بدون تقاطع." },
  { id: "H252", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تتذكر تفاصيل صغيرة قالها أصحابك من قبل." },
  { id: "H253", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا أحد احتاج مساعدة تعرض قبل ما يطلب." },
  { id: "H254", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تحب القعدة اللي فيها ألعاب جماعية." },
  { id: "H255", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تفضّل الزيارات القصيرة المتكررة على زيارة طويلة." },
  { id: "H256", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا صارت لحظة محرجة تغيّر الموضوع بسرعة." },
  { id: "H257", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تحب تستضيف الناس عندك أكثر من تطلع." },
  { id: "H258", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا ترد على الدعوة بسرعة بدل تخليها معلقة." },
  { id: "H259", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا أحد جديد بالشلة تسأله أسئلة عشان يتعرف عليكم." },
  { id: "H260", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تحب تسولف وأنت تمشي أكثر من القعدة الرسمية." },
  { id: "H261", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تلاحظ بسرعة إذا واحد من الموجودين مو على جوه." },
  { id: "H262", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تفضّل تتفقون على الحساب من البداية إذا الطلب جماعي." },
  { id: "H263", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا اختلفت مع صاحبك تفضّل تكلمه مباشرة." },
  { id: "H264", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تحب المناسبات اللي فيها ناس تعرفهم من أكثر من دائرة." },
  { id: "H265", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تفضّل الهدوء بعد جمعة طويلة." },
  { id: "H266", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تجرب طريقة جديدة حتى لو القديمة شغالة." },
  { id: "H267", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا عندك خيارين حلوين تختار بسرعة وما ترجع تفكر." },
  { id: "H268", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تحب تسأل أكثر من شخص قبل قرار كبير." },
  { id: "H269", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تفضّل الجودة حتى لو دفعت أكثر شوي." },
  { id: "H270", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تغير رأيك إذا سمعت حجة قوية." },
  { id: "H271", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تحب تبدأ الشي وتجرب بدل تقرأ عنه كثير." },
  { id: "H272", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا صار خطأ بسيط تقدر تكمل يومك عادي." },
  { id: "H273", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تفضّل المنافسة الخفيفة على اللعب بدون نتيجة." },
  { id: "H274", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تحب تتعلم مهارة بيدك أكثر من مشاهدة شرح طويل." },
  { id: "H275", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا أحد عطاك اختيار مفاجئ غالبًا تمشي مع أول إحساس." },
  { id: "H276", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تفضّل الأماكن المعروفة إذا كنت مستعجل." },
  { id: "H277", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تحب تغير ترتيب يومك بين فترة وفترة." },
  { id: "H278", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا ما فهمت شي تسأل مباشرة." },
  { id: "H279", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تفضّل تسوي شي واحد بتركيز على عدة أشياء مع بعض." },
  { id: "H280", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تحب تكافئ نفسك بعد ما تخلص مهمة ثقيلة." },
  { id: "H281", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا فشلت أول مرة تعيد المحاولة بسرعة." },
  { id: "H282", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تفضّل تخلص النقاش قبل ما تنام." },
  { id: "H283", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تحب الأشياء البسيطة اللي ما تحتاج تجهيز كثير." },
  { id: "H284", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا عندك وقت فاضي تعرف بسرعة وش تسوي فيه." },
  { id: "H285", mode: "HANDS", family: "personality-decisions", text: "ارفع يدك إذا تحب تكون عندك خيارات بدل خطة واحدة ثابتة." },
  { id: "H286", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تحب تتعلم وصفة جديدة من أحد من أهلك." },
  { id: "H287", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تتذكر أعياد ميلاد المقربين بدون تنبيه." },
  { id: "H288", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تحب تساعد بتجهيز السفرة قبل الأكل." },
  { id: "H289", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا رجعت البيت تسلم على الموجودين قبل أي شي." },
  { id: "H290", mode: "HANDS", family: "social-gatherings", text: "ارفع يدك إذا تفضّل تجلس مع كبار العائلة وتسمع سوالفهم." },
];
