import type { ImitationPrompt } from "./imitationPrompts.data.js";

export const EXPANSION_POINT_4_PROMPTS: ImitationPrompt[] = [
  { id: "P196", mode: "POINT", family: "planning-time", text: "أشر على اللي لو عندكم وقت محدود بيقول وش الأشياء اللي ممكن نستغني عنها." },
  { id: "P197", mode: "POINT", family: "planning-time", text: "أشر على اللي لو واحد نسى شي مهم بيقدر يعدّل الخطة بدون توتر." },
  { id: "P198", mode: "POINT", family: "planning-time", text: "أشر على اللي لو عندكم طلعة بعشرة أشخاص بيحاول يثبت التفاصيل بدري." },
  { id: "P199", mode: "POINT", family: "planning-time", text: "أشر على اللي لو الموعد تأجل ساعة بيعرف يستفيد من الوقت الفاضي." },
  { id: "P200", mode: "POINT", family: "planning-time", text: "أشر على اللي لو مهمتين بنفس الأهمية بيبدأ بالأقرب للإنجاز." },
  { id: "P201", mode: "POINT", family: "planning-time", text: "أشر على اللي لو عندكم قائمة طويلة يفرح كل ما تشطبون منها شي." },
  { id: "P202", mode: "POINT", family: "planning-time", text: "أشر على اللي لو أحد قال «ما يفرق معي» في اختيار المكان بيعطيه خيارين محددين." },
  { id: "P203", mode: "POINT", family: "shopping-money", text: "أشر على اللي لو شاف شي يعجبه بس سعره عالي بينتظر قبل يشتري." },
  { id: "P204", mode: "POINT", family: "shopping-money", text: "أشر على اللي لو عطيتوه ميزانية لهدية بيطلع أفضل فكرة ضمنها." },
  { id: "P205", mode: "POINT", family: "shopping-money", text: "أشر على اللي لو دخل متجر كبير يعرف وش يبي وما يلف كثير." },
  { id: "P206", mode: "POINT", family: "shopping-money", text: "أشر على اللي لو فيه عرض «اشتر اثنين» بيسأل أول هل نحتاج الثاني فعلًا." },
  { id: "P207", mode: "POINT", family: "shopping-money", text: "أشر على اللي لو اشترى شي جديد يحتفظ بالكرتون والفاتورة فترة." },
  { id: "P208", mode: "POINT", family: "shopping-money", text: "أشر على اللي لو عندكم مشتريات للجَمعة بيحسب الكمية أقرب للصح." },
  { id: "P209", mode: "POINT", family: "shopping-money", text: "أشر على اللي لو شاف منتج عليه ضجة بيدور مراجعات قبل يقتنع." },
  { id: "P210", mode: "POINT", family: "shopping-money", text: "أشر على اللي لو اختار هدية لشخص بيعتمد على شخصيته مو على اللي هو يحبه." },
  { id: "P211", mode: "POINT", family: "shopping-money", text: "أشر على اللي لو عنده مبلغ زيادة بسيط ممكن يوفره بدل يصرفه مباشرة." },
  { id: "P212", mode: "POINT", family: "shopping-money", text: "أشر على اللي لو اشترى شي وما ناسبه بيرجعه بدل يخليه بالبيت." },
  { id: "P213", mode: "POINT", family: "shopping-money", text: "أشر على اللي لو دخلتم سوبرماركت معه بيذكركم بالأشياء الأساسية." },
  { id: "P214", mode: "POINT", family: "home-routine", text: "أشر على اللي لو البيت يحتاج ترتيب بيبدأ بمنطقة صغيرة ويكمل." },
  { id: "P215", mode: "POINT", family: "home-routine", text: "أشر على اللي لو انكسر شي بسيط بالبيت بيحاول يصلحه أول." },
  { id: "P216", mode: "POINT", family: "home-routine", text: "أشر على اللي لو كل واحد عنده أغراض بالصالة بيجمع أغراضه أول بدون ما يطلب منه." },
  { id: "P217", mode: "POINT", family: "home-routine", text: "أشر على اللي لو ضاع مفتاح بالبيت بيدور بطريقة منظمة غرفة غرفة." },
  { id: "P218", mode: "POINT", family: "home-routine", text: "أشر على اللي لو الطبخ خلص بيبدأ يرتب المطبخ قبل ما تتراكم الأشياء." },
  { id: "P219", mode: "POINT", family: "home-routine", text: "أشر على اللي لو عندكم أغراض كثيرة قديمة يقدر يتخلص منها أسهل." },
  { id: "P220", mode: "POINT", family: "home-routine", text: "أشر على اللي لو غيرتوا ترتيب الغرفة بيتأقلم بسرعة وما يرجع كل شي مكانه." },
  { id: "P221", mode: "POINT", family: "home-routine", text: "أشر على اللي لو فيه شي ناقص بالبيت غالبًا يلاحظه قبل لا يخلص تمامًا." },
  { id: "P222", mode: "POINT", family: "home-routine", text: "أشر على اللي لو عندكم ضيوف بعد ساعة بيعرف وش أهم الأشياء اللي تتسوى أول." },
  { id: "P223", mode: "POINT", family: "music-media", text: "أشر على اللي لو فتحتوا فيلم وما عجبكم بعد 20 دقيقة بيقول غيروه." },
  { id: "P224", mode: "POINT", family: "music-media", text: "أشر على اللي لو نزل مسلسل كامل بيقدر يمنع نفسه من حرقه بليلة وحدة." },
  { id: "P225", mode: "POINT", family: "music-media", text: "أشر على اللي لو عطيتوه التحكم بالأغاني بيعرف يختار شي يناسب الجميع." },
  { id: "P226", mode: "POINT", family: "music-media", text: "أشر على اللي لو شغلت أغنية ما يعرفها بيعطيها فرصة قبل يغير." },
  { id: "P227", mode: "POINT", family: "music-media", text: "أشر على اللي لو عندكم لعبة جديدة بيفهم القوانين ويشرحها للباقين." },
  { id: "P228", mode: "POINT", family: "music-media", text: "أشر على اللي لو خسر بفارق بسيط بيطلب إعادة بحماس مو بعصبية." },
  { id: "P229", mode: "POINT", family: "sports-games", text: "أشر على اللي لو شاف لقطة قوية بمباراة بيرجع يشوف الإعادة." },
  { id: "P230", mode: "POINT", family: "sports-games", text: "أشر على اللي لو الكل يبي فيلم مختلف بيطلع حل وسط معقول." },
];
