/**
 * Curated question pairs for «خلك طبيعي».
 *
 * Each pair gives normal players `normalQuestion` and the single impostor
 * `impostorQuestion`. The two questions should lead to overlapping answer
 * pools without being identical. Copy is intentionally natural Saudi/Gulf
 * Arabic, family-friendly, short, and conversational.
 *
 * Editorial rule: if players can identify the role from the answer type alone,
 * the pair is too far apart. If both questions are effectively identical, the
 * pair is too close.
 */
import type { CategoryId } from "../../../shared/types.js";

export interface QuestionPair {
  id: string;
  category: CategoryId;
  normalQuestion: string;
  impostorQuestion: string;
  /** Content pack this pair belongs to. The default family pack is "core". */
  pack: string;
  difficulty?: "easy" | "medium" | "hard";
}

/**
 * Family-friendly Saudi/Gulf core pack.
 *
 * Difficulty is editorial metadata only for now:
 * - easy: clearer distinction but still plausible overlap
 * - medium: balanced default
 * - hard: subtler distinction and broader overlap
 */
export const CORE_PACK: QuestionPair[] = [
  // ---------------------- العائلة (family) ----------------------
  { id: "fam_01", category: "family", pack: "core", difficulty: "medium",
    normalQuestion: "إذا اجتمعت العائلة بالويكند، وش غالبًا تسوون؟",
    impostorQuestion: "إذا اجتمعت العائلة بالإجازة، وش غالبًا تسوون؟" },
  { id: "fam_02", category: "family", pack: "core", difficulty: "easy",
    normalQuestion: "وش الشي اللي دايم تلقاه في بيت الأهل؟",
    impostorQuestion: "وش الشي اللي دايم تلقاه في مطبخ الأهل؟" },
  { id: "fam_03", category: "family", pack: "core", difficulty: "medium",
    normalQuestion: "إذا رحت تزور جدتك، وش غالبًا تاخذ معك؟",
    impostorQuestion: "إذا رحت تزور خالتك، وش غالبًا تاخذ معك؟" },
  { id: "fam_04", category: "family", pack: "core", difficulty: "hard",
    normalQuestion: "وش أكثر غرض الكل يحتاجه بالبيت؟",
    impostorQuestion: "وش أكثر غرض الكل يدور عليه بالبيت؟" },
  { id: "fam_05", category: "family", pack: "core", difficulty: "medium",
    normalQuestion: "إذا دخلت البيت متأخر، وش أول شي ينقال لك؟",
    impostorQuestion: "إذا صحيت متأخر، وش أول شي ينقال لك؟" },
  { id: "fam_06", category: "family", pack: "core", difficulty: "easy",
    normalQuestion: "وش الشي اللي يجمع العائلة على سفرة وحدة؟",
    impostorQuestion: "وش الشي اللي يجمع العائلة قدام شاشة وحدة؟" },
  { id: "fam_07", category: "family", pack: "core", difficulty: "medium",
    normalQuestion: "لو تبي تفرّح أمك، وش تسوي؟",
    impostorQuestion: "لو تبي تفرّح أبوك، وش تسوي؟" },
  { id: "fam_08", category: "family", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي تشتاق له من أيام الطفولة؟",
    impostorQuestion: "وش أكثر شي تشتاق له من أيام المدرسة؟" },
  { id: "fam_09", category: "family", pack: "core", difficulty: "easy",
    normalQuestion: "لو بتجيب هدية لأمك، وش تختار؟",
    impostorQuestion: "لو بتجيب هدية لجدتك، وش تختار؟" },
  { id: "fam_10", category: "family", pack: "core", difficulty: "medium",
    normalQuestion: "إذا صار عندكم مولود جديد، وش أول شي تسوونه؟",
    impostorQuestion: "إذا تخرج واحد من العائلة، وش أول شي تسوونه؟" },
  { id: "fam_11", category: "family", pack: "core", difficulty: "hard",
    normalQuestion: "وين غالبًا تطلع أحلى صور العائلة؟",
    impostorQuestion: "متى غالبًا تطلع أحلى صور العائلة؟" },
  { id: "fam_12", category: "family", pack: "core", difficulty: "medium",
    normalQuestion: "إذا كنت مسافر، وش أكثر شي تسأل عنه أهلك؟",
    impostorQuestion: "إذا رجعت من سفر، وش أكثر شي تسأل عنه أهلك؟" },

  // ---------------------- الأصحاب (friends) ----------------------
  { id: "frn_01", category: "friends", pack: "core", difficulty: "easy",
    normalQuestion: "إذا طلعتوا بالليل، وين غالبًا تروحون؟",
    impostorQuestion: "إذا طلعتوا بعد الدوام، وين غالبًا تروحون؟" },
  { id: "frn_02", category: "friends", pack: "core", difficulty: "medium",
    normalQuestion: "وش الشي اللي غالبًا تاخذونه معكم للطلعة؟",
    impostorQuestion: "وش الشي اللي غالبًا يكون معكم بالاستراحة؟" },
  { id: "frn_03", category: "friends", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي يأخر الشلة عن الموعد؟",
    impostorQuestion: "وش أكثر شي يخلي الطلعة تتأجل؟" },
  { id: "frn_04", category: "friends", pack: "core", difficulty: "medium",
    normalQuestion: "وش اللعبة اللي تمشي وقت الاستراحة؟",
    impostorQuestion: "وش اللعبة اللي تمشي وقت السفر بالسيارة؟" },
  { id: "frn_05", category: "friends", pack: "core", difficulty: "hard",
    normalQuestion: "وش الصفة اللي تخليك ترتاح لصاحبك؟",
    impostorQuestion: "وش الصفة اللي تخليك تعتمد على صاحبك؟" },
  { id: "frn_06", category: "friends", pack: "core", difficulty: "hard",
    normalQuestion: "وش الشي اللي يخلي جمعة الشلة تضبط؟",
    impostorQuestion: "وش الشي اللي يخلي طلعة الشلة تضبط؟" },
  { id: "frn_07", category: "friends", pack: "core", difficulty: "medium",
    normalQuestion: "إذا شفت صاحبك بعد غيبة، وش أول شي تسويه؟",
    impostorQuestion: "إذا كلمت صاحبك بعد غيبة، وش أول شي تقوله؟" },
  { id: "frn_08", category: "friends", pack: "core", difficulty: "easy",
    normalQuestion: "وش الطلعة اللي ما تملون منها؟",
    impostorQuestion: "وش القعدة اللي ما تملون منها؟" },
  { id: "frn_09", category: "friends", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي يفتح سالفة بالشلة؟",
    impostorQuestion: "وش أكثر شي يقلب القعدة ضحك بالشلة؟" },
  { id: "frn_10", category: "friends", pack: "core", difficulty: "medium",
    normalQuestion: "إذا تزوج واحد من الشلة، وش غالبًا تسوون له؟",
    impostorQuestion: "إذا رجع واحد من الشلة من سفر، وش غالبًا تسوون له؟" },
  { id: "frn_11", category: "friends", pack: "core", difficulty: "easy",
    normalQuestion: "إذا قعدتوا بكوفي، وش غالبًا تطلبون؟",
    impostorQuestion: "إذا قعدتوا بمطعم، وش غالبًا تطلبون؟" },
  { id: "frn_12", category: "friends", pack: "core", difficulty: "hard",
    normalQuestion: "بأي موقف تعتمد على صاحبك أكثر؟",
    impostorQuestion: "بأي موقف تحتاج الشلة أكثر؟" },

  // ---------------------- الأكل والشرب السعودي (food) ----------------------
  { id: "fud_01", category: "food", pack: "core", difficulty: "easy",
    normalQuestion: "وش أحسن شي يجي مع الكبسة؟",
    impostorQuestion: "وش أحسن شي يجي مع المندي؟" },
  { id: "fud_02", category: "food", pack: "core", difficulty: "hard",
    normalQuestion: "وش غالبًا تاكل مع القهوة؟",
    impostorQuestion: "وش غالبًا تاكل مع الشاهي؟" },
  { id: "fud_03", category: "food", pack: "core", difficulty: "medium",
    normalQuestion: "وش أول شي تحطه بصحن الفطور؟",
    impostorQuestion: "وش أول شي تحطه بصحن العشا؟" },
  { id: "fud_04", category: "food", pack: "core", difficulty: "medium",
    normalQuestion: "إذا ما لك خلق تطبخ، وش غالبًا تطلب؟",
    impostorQuestion: "إذا تبي تسوي شي سريع بالبيت، وش غالبًا تطبخ؟" },
  { id: "fud_05", category: "food", pack: "core", difficulty: "medium",
    normalQuestion: "وش تحب تضيف على الرز؟",
    impostorQuestion: "وش تحب تضيف على المعكرونة؟" },
  { id: "fud_06", category: "food", pack: "core", difficulty: "easy",
    normalQuestion: "وش الحلا اللي يناسب بعد العشا؟",
    impostorQuestion: "وش الحلا اللي يناسب مع القهوة؟" },
  { id: "fud_07", category: "food", pack: "core", difficulty: "hard",
    normalQuestion: "إذا جربت مطعم جديد، وش تميل تطلب؟",
    impostorQuestion: "إذا رجعت لمطعمك المفضل، وش تميل تطلب؟" },
  { id: "fud_08", category: "food", pack: "core", difficulty: "easy",
    normalQuestion: "أي نكهة تختار بالآيسكريم؟",
    impostorQuestion: "أي نكهة تختار بالميلك شيك؟" },
  { id: "fud_09", category: "food", pack: "core", difficulty: "medium",
    normalQuestion: "في يوم حر، وش أول مشروب يخطر ببالك؟",
    impostorQuestion: "في يوم برد، وش أول مشروب يخطر ببالك؟" },
  { id: "fud_10", category: "food", pack: "core", difficulty: "hard",
    normalQuestion: "وش النوع اللي تفضله من التمر؟",
    impostorQuestion: "وش النوع اللي تفضله من العسل؟" },
  { id: "fud_11", category: "food", pack: "core", difficulty: "medium",
    normalQuestion: "وش الشي اللي يخليك تتحمس للأكل؟",
    impostorQuestion: "وش الشي اللي يخليك تشتهي وجبة؟" },
  { id: "fud_12", category: "food", pack: "core", difficulty: "medium",
    normalQuestion: "إذا جاك ضيف على القهوة، وش تقدم معه؟",
    impostorQuestion: "إذا جاك ضيف بعد العشا، وش تقدم له؟" },
  { id: "fud_13", category: "food", pack: "core", difficulty: "easy",
    normalQuestion: "وش غالبًا يكون فطوركم يوم الجمعة؟",
    impostorQuestion: "وش غالبًا يكون غداكم يوم الجمعة؟" },
  { id: "fud_14", category: "food", pack: "core", difficulty: "medium",
    normalQuestion: "إذا دخلت بقالة وأنت جوعان، وش أول شي تشتري؟",
    impostorQuestion: "إذا دخلت بقالة وأنت عطشان، وش أول شي تشتري؟" },

  // ---------------------- المدن والسفر (travel) ----------------------
  { id: "trv_01", category: "travel", pack: "core", difficulty: "easy",
    normalQuestion: "وش تاخذ معك لطلعة البر؟",
    impostorQuestion: "وش تاخذ معك للبحر؟" },
  { id: "trv_02", category: "travel", pack: "core", difficulty: "medium",
    normalQuestion: "وين تحب تروح داخل السعودية بالصيف؟",
    impostorQuestion: "وين تحب تروح داخل السعودية بالشتاء؟" },
  { id: "trv_03", category: "travel", pack: "core", difficulty: "hard",
    normalQuestion: "إذا بتسافر، وش أول شي ترتبه؟",
    impostorQuestion: "إذا بتطلع رحلة قصيرة، وش أول شي ترتبه؟" },
  { id: "trv_04", category: "travel", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي ممكن تنساه بالسفر؟",
    impostorQuestion: "وش أكثر شي ممكن تنساه بالكشتة؟" },
  { id: "trv_05", category: "travel", pack: "core", difficulty: "medium",
    normalQuestion: "لو عندك يوم واحد بمدينة جديدة، وين تبدأ؟",
    impostorQuestion: "لو عندك ليلة وحدة بمدينة جديدة، وين تبدأ؟" },
  { id: "trv_06", category: "travel", pack: "core", difficulty: "easy",
    normalQuestion: "وش تسوي بالطيارة عشان الوقت يمشي؟",
    impostorQuestion: "وش تسوي بالسيارة في سفر طويل عشان الوقت يمشي؟" },
  { id: "trv_07", category: "travel", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي يعجبك بأبها؟",
    impostorQuestion: "وش أكثر شي يعجبك بالطايف؟" },
  { id: "trv_08", category: "travel", pack: "core", difficulty: "medium",
    normalQuestion: "إذا رجعت من سفر، وش غالبًا تجيب لأهلك؟",
    impostorQuestion: "إذا رجعت من سفر، وش غالبًا تجيب لأصحابك؟" },
  { id: "trv_09", category: "travel", pack: "core", difficulty: "hard",
    normalQuestion: "وش أهم شي عندك إذا اخترت فندق؟",
    impostorQuestion: "وش أهم شي عندك إذا اخترت شاليه؟" },
  { id: "trv_10", category: "travel", pack: "core", difficulty: "hard",
    normalQuestion: "إذا طلعت بر، وين تحب تكون جلستك؟",
    impostorQuestion: "إذا رحت مخيم، وين تحب تكون جلستك؟" },
  { id: "trv_11", category: "travel", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي يكدّر عليك السفر؟",
    impostorQuestion: "وش أكثر شي يكدّر عليك الطلعة؟" },
  { id: "trv_12", category: "travel", pack: "core", difficulty: "medium",
    normalQuestion: "إذا وصلت مدينة أول مرة، وش أول مكان تدوره؟",
    impostorQuestion: "إذا وصلت مدينة أول مرة، وش أول شي ودك تجربه؟" },

  // ---------------------- كرة القدم (football) ----------------------
  { id: "fut_01", category: "football", pack: "core", difficulty: "medium",
    normalQuestion: "وش أهم شي يخلي الفريق يفوز؟",
    impostorQuestion: "وش أهم شي يخلي اللاعب يبرز؟" },
  { id: "fut_02", category: "football", pack: "core", difficulty: "easy",
    normalQuestion: "إذا خسر فريقك مباراة مهمة، وش تسوي بعدها؟",
    impostorQuestion: "إذا فاز فريقك مباراة مهمة، وش تسوي بعدها؟" },
  { id: "fut_03", category: "football", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي يعصبك وأنت تتابع مباراة؟",
    impostorQuestion: "وش أكثر شي يرفع حماسك وأنت تتابع مباراة؟" },
  { id: "fut_04", category: "football", pack: "core", difficulty: "hard",
    normalQuestion: "وين تحب تتابع المباراة الكبيرة؟",
    impostorQuestion: "وين تحب تتابع نهائي بطولة؟" },
  { id: "fut_05", category: "football", pack: "core", difficulty: "medium",
    normalQuestion: "وش أهم شي تجهزه قبل مباراة كبيرة؟",
    impostorQuestion: "وش أهم شي تجهزه قبل ما تروح للملعب؟" },
  { id: "fut_06", category: "football", pack: "core", difficulty: "hard",
    normalQuestion: "وش أهم مركز بالفريق بنظرك؟",
    impostorQuestion: "وش أصعب مركز بالفريق بنظرك؟" },
  { id: "fut_07", category: "football", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي يخلي الدوري ممتع؟",
    impostorQuestion: "وش أكثر شي يخلي البطولة ممتعة؟" },
  { id: "fut_08", category: "football", pack: "core", difficulty: "medium",
    normalQuestion: "إذا لعبت مع أصحابك، أي مركز تختار؟",
    impostorQuestion: "إذا لعبت مباراة حواري، أي مركز تختار؟" },
  { id: "fut_09", category: "football", pack: "core", difficulty: "hard",
    normalQuestion: "وش أكثر شي يرفع حماس المدرجات؟",
    impostorQuestion: "وش أكثر شي يرفع حماس اللاعبين؟" },
  { id: "fut_10", category: "football", pack: "core", difficulty: "easy",
    normalQuestion: "إذا رحت تشجع بالملعب، وش تلبس؟",
    impostorQuestion: "إذا رحت تشجع بالملعب، وش تاخذ معك؟" },
  { id: "fut_11", category: "football", pack: "core", difficulty: "medium",
    normalQuestion: "وش المباراة اللي ما ودك تفوتها بالموسم؟",
    impostorQuestion: "وش المباراة اللي ودك تحضرها بالملعب؟" },
  { id: "fut_12", category: "football", pack: "core", difficulty: "hard",
    normalQuestion: "إذا صاحبك يشجع خصمك، وش أكثر جملة تقولها له؟",
    impostorQuestion: "إذا خسر فريق صاحبك، وش أكثر جملة تقولها له؟" },

  // ---------------------- رمضان والعيد (ramadan) ----------------------
  { id: "rmd_01", category: "ramadan", pack: "core", difficulty: "easy",
    normalQuestion: "وش أول شي تفطر عليه برمضان؟",
    impostorQuestion: "وش أول شي تبدأ فيه السحور؟" },
  { id: "rmd_02", category: "ramadan", pack: "core", difficulty: "medium",
    normalQuestion: "وش الشي اللي ما ينقص من سفرة الفطور؟",
    impostorQuestion: "وش الشي اللي ما ينقص من سفرة السحور؟" },
  { id: "rmd_03", category: "ramadan", pack: "core", difficulty: "medium",
    normalQuestion: "بعد التراويح، وش غالبًا تسوي؟",
    impostorQuestion: "قبل الفطور بساعة، وش غالبًا تسوي؟" },
  { id: "rmd_04", category: "ramadan", pack: "core", difficulty: "easy",
    normalQuestion: "وأنت صايم، وش أكثر شي تشتهيه؟",
    impostorQuestion: "أول ما تفطر، وش أكثر شي تبيه؟" },
  { id: "rmd_05", category: "ramadan", pack: "core", difficulty: "medium",
    normalQuestion: "وش أهم شي تجهزه لأول يوم عيد؟",
    impostorQuestion: "وش أهم شي تختاره لأول يوم عيد؟" },
  { id: "rmd_06", category: "ramadan", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي يعطي ليلة العيد جوها؟",
    impostorQuestion: "وش أكثر شي يعطي صباح العيد جوه؟" },
  { id: "rmd_07", category: "ramadan", pack: "core", difficulty: "easy",
    normalQuestion: "وش أكثر شي يفرح الأطفال بالعيد؟",
    impostorQuestion: "وش أكثر شي ينتظرونه الأطفال بالعيد؟" },
  { id: "rmd_08", category: "ramadan", pack: "core", difficulty: "medium",
    normalQuestion: "وش غالبًا تقدمون للضيوف بالعيد؟",
    impostorQuestion: "وش غالبًا تقدمون للضيوف برمضان؟" },
  { id: "rmd_09", category: "ramadan", pack: "core", difficulty: "hard",
    normalQuestion: "وش أكثر شي تشوفه على سفرة رمضان؟",
    impostorQuestion: "وش أكثر شي يخلص بسرعة من سفرة رمضان؟" },
  { id: "rmd_10", category: "ramadan", pack: "core", difficulty: "medium",
    normalQuestion: "أول يوم عيد، وين غالبًا تروح؟",
    impostorQuestion: "ثاني يوم عيد، وين غالبًا تروح؟" },
  { id: "rmd_11", category: "ramadan", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر عادة تحافظ عليها بالعشر الأواخر؟",
    impostorQuestion: "وش أكثر عادة تبدأ فيها أول رمضان؟" },
  { id: "rmd_12", category: "ramadan", pack: "core", difficulty: "hard",
    normalQuestion: "وش أكثر شي يميز جو رمضان بالنسبة لك؟",
    impostorQuestion: "وش أكثر شي يميز جو العيد بالنسبة لك؟" },

  // ---------------------- سوالف المجلس (majlis) ----------------------
  { id: "mjl_01", category: "majlis", pack: "core", difficulty: "easy",
    normalQuestion: "إذا جا ضيف للمجلس، وش أول شي تقدمه له؟",
    impostorQuestion: "إذا طال المجلس، وش غالبًا تقدمه للضيف بعدين؟" },
  { id: "mjl_02", category: "majlis", pack: "core", difficulty: "medium",
    normalQuestion: "وش الموضوع اللي يفتح السوالف بالمجلس؟",
    impostorQuestion: "وش الموضوع اللي يخلي السوالف تطول بالمجلس؟" },
  { id: "mjl_03", category: "majlis", pack: "core", difficulty: "hard",
    normalQuestion: "وش الشي اللي ما تنجح بدونه جمعة العيال؟",
    impostorQuestion: "وش الشي اللي ما تنجح بدونه جمعة الشباب؟" },
  { id: "mjl_04", category: "majlis", pack: "core", difficulty: "medium",
    normalQuestion: "في جمعة الخميس، وش غالبًا تسوون؟",
    impostorQuestion: "في جمعة الجمعة، وش غالبًا تسوون؟" },
  { id: "mjl_05", category: "majlis", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي يخلي المجلس مريح؟",
    impostorQuestion: "وش أكثر شي يخلي الاستراحة مريحة؟" },
  { id: "mjl_06", category: "majlis", pack: "core", difficulty: "hard",
    normalQuestion: "أول ما تدخل مجلس، وش أول شي تسويه؟",
    impostorQuestion: "قبل ما تطلع من مجلس، وش آخر شي تسويه؟" },
  { id: "mjl_07", category: "majlis", pack: "core", difficulty: "medium",
    normalQuestion: "وش غالبًا ينقدم قبل العشا للضيوف؟",
    impostorQuestion: "وش غالبًا ينقدم بعد العشا للضيوف؟" },
  { id: "mjl_08", category: "majlis", pack: "core", difficulty: "medium",
    normalQuestion: "وش السالفة اللي كبار السن يحبونها بالمجلس؟",
    impostorQuestion: "وش السالفة اللي الشباب يحبونها بالمجلس؟" },
  { id: "mjl_09", category: "majlis", pack: "core", difficulty: "hard",
    normalQuestion: "وش الشي اللي يخلي الضيف يطول بالقعدة؟",
    impostorQuestion: "وش الشي اللي يخلي القعدة تطول من غير ما تحسون؟" },
  { id: "mjl_10", category: "majlis", pack: "core", difficulty: "medium",
    normalQuestion: "وش غالبًا تحط بوسط المجلس؟",
    impostorQuestion: "وش غالبًا تحط على طاولة المجلس؟" },
  { id: "mjl_11", category: "majlis", pack: "core", difficulty: "hard",
    normalQuestion: "إذا سكت المجلس فجأة، وش تسوي؟",
    impostorQuestion: "إذا هدت السوالف بالمجلس، وش تسوي؟" },

  // ---------------------- الجامعة والعمل (work) ----------------------
  { id: "wrk_01", category: "work", pack: "core", difficulty: "easy",
    normalQuestion: "أول ما توصل الدوام، وش أول شي تسويه؟",
    impostorQuestion: "أول ما توصل الجامعة، وش أول شي تسويه؟" },
  { id: "wrk_02", category: "work", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي يأخرك عن الدوام؟",
    impostorQuestion: "وش أكثر شي يأخرك عن المحاضرة؟" },
  { id: "wrk_03", category: "work", pack: "core", difficulty: "easy",
    normalQuestion: "وش تشرب عشان تصحصح بالدوام؟",
    impostorQuestion: "وش تشرب عشان تصحصح وقت المذاكرة؟" },
  { id: "wrk_04", category: "work", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي يطفشك بالاجتماعات؟",
    impostorQuestion: "وش أكثر شي يطفشك بالمحاضرات؟" },
  { id: "wrk_05", category: "work", pack: "core", difficulty: "easy",
    normalQuestion: "في بريك الدوام، وش غالبًا تسوي؟",
    impostorQuestion: "بين المحاضرات، وش غالبًا تسوي؟" },
  { id: "wrk_06", category: "work", pack: "core", difficulty: "hard",
    normalQuestion: "وش أهم صفة بزميل الدوام؟",
    impostorQuestion: "وش أهم صفة بزميل الدراسة؟" },
  { id: "wrk_07", category: "work", pack: "core", difficulty: "medium",
    normalQuestion: "ليلة قبل مقابلة مهمة، وش تجهز؟",
    impostorQuestion: "ليلة قبل عرض مهم، وش تجهز؟" },
  { id: "wrk_08", category: "work", pack: "core", difficulty: "medium",
    normalQuestion: "وش الشي اللي يحسن مزاجك بالدوام؟",
    impostorQuestion: "وش الشي اللي يحسن مزاجك بالجامعة؟" },
  { id: "wrk_09", category: "work", pack: "core", difficulty: "easy",
    normalQuestion: "وش الشي اللي دايم تاخذه معك للدوام؟",
    impostorQuestion: "وش الشي اللي دايم تاخذه معك للجامعة؟" },
  { id: "wrk_10", category: "work", pack: "core", difficulty: "hard",
    normalQuestion: "آخر ساعة بالدوام، وش غالبًا تسوي؟",
    impostorQuestion: "آخر ساعة قبل نهاية يوم الجامعة، وش غالبًا تسوي؟" },
  { id: "wrk_11", category: "work", pack: "core", difficulty: "medium",
    normalQuestion: "وش أكثر شي يخليك تفكر تغير وظيفتك؟",
    impostorQuestion: "وش أكثر شي يخليك تفكر تغير تخصصك؟" },
  { id: "wrk_12", category: "work", pack: "core", difficulty: "medium",
    normalQuestion: "بعد التخرج، وش أول شي تتمنى يصير؟",
    impostorQuestion: "بعد أول وظيفة، وش أول شي تتمنى يصير؟" },

  // ---------------------- أسئلة عامة خفيفة (general) ----------------------
  { id: "gen_01", category: "general", pack: "core", difficulty: "easy",
    normalQuestion: "أول ما تصحى، وش أول شي تسويه؟",
    impostorQuestion: "قبل ما تنام، وش آخر شي تسويه؟" },
  { id: "gen_02", category: "general", pack: "core", difficulty: "medium",
    normalQuestion: "إذا طلعت من البيت بسرعة، وش أهم شي تاخذه؟",
    impostorQuestion: "إذا طلعت من البيت بسرعة، وش أكثر شي تنساه؟" },
  { id: "gen_03", category: "general", pack: "core", difficulty: "hard",
    normalQuestion: "وش أكثر تطبيق تفتحه خلال اليوم؟",
    impostorQuestion: "وش أكثر تطبيق يضيع وقتك خلال اليوم؟" },
  { id: "gen_04", category: "general", pack: "core", difficulty: "medium",
    normalQuestion: "إذا طفشت، وش غالبًا تسوي؟",
    impostorQuestion: "إذا فضيت فجأة، وش غالبًا تسوي؟" },
  { id: "gen_05", category: "general", pack: "core", difficulty: "medium",
    normalQuestion: "لو جاك مبلغ كبير، وش أول شي تشتريه؟",
    impostorQuestion: "لو جاك مبلغ كبير، وش أول شي تدفعه؟" },
  { id: "gen_06", category: "general", pack: "core", difficulty: "easy",
    normalQuestion: "إذا جا مطر، وش ودك تسوي؟",
    impostorQuestion: "إذا صار الجو بارد، وش ودك تسوي؟" },
  { id: "gen_07", category: "general", pack: "core", difficulty: "hard",
    normalQuestion: "وش اللون اللي تلبسه كثير؟",
    impostorQuestion: "وش اللون اللي تختاره إذا احتجت شي رسمي؟" },
  { id: "gen_08", category: "general", pack: "core", difficulty: "medium",
    normalQuestion: "وأنت تسوق، وش تحب تسمع؟",
    impostorQuestion: "وأنت تشتغل أو تذاكر، وش تحب تسمع؟" },
  { id: "gen_09", category: "general", pack: "core", difficulty: "hard",
    normalQuestion: "وش الغرض اللي ما تحب تعيره أحد؟",
    impostorQuestion: "وش الغرض اللي ما تحب تستلفه من أحد؟" },
  { id: "gen_10", category: "general", pack: "core", difficulty: "medium",
    normalQuestion: "إذا توترت، وش الشي اللي يساعدك تهدأ؟",
    impostorQuestion: "إذا تعبت، وش الشي اللي يساعدك ترتاح؟" },
  { id: "gen_11", category: "general", pack: "core", difficulty: "easy",
    normalQuestion: "وش تحب تسوي بالويكند؟",
    impostorQuestion: "وش تحب تسوي بالإجازة الطويلة؟" },
  { id: "gen_12", category: "general", pack: "core", difficulty: "hard",
    normalQuestion: "وش شي ودك لو سويته من زمان؟",
    impostorQuestion: "وش شي مبسوط إنك سويته من زمان؟" },
  { id: "gen_13", category: "general", pack: "core", difficulty: "medium",
    normalQuestion: "أول ما تقابل شخص، وش أول شي تلاحظه؟",
    impostorQuestion: "بعد ما تودع شخص، وش أكثر شي تتذكره عنه؟" },
];
