/**
 * Curated question pairs for «خلك طبيعي».
 *
 * Each pair gives normal players `normalQuestion` and the single impostor
 * `impostorQuestion`. The two questions are deliberately close so their
 * answers overlap and the impostor can hide — the fun is in the ambiguity.
 *
 * CONTENT RULES: natural Saudi/Gulf Arabic, family-friendly, no offensive
 * content, no literal English phrasing, short conversational answers.
 *
 * To add a pack later, create another array of `QuestionPair` with a distinct
 * `pack` value and merge it in `questions.ts`. The engine never needs changing.
 */
import type { CategoryId } from "../../../shared/types.js";

export interface QuestionPair {
  id: string;
  category: CategoryId;
  normalQuestion: string;
  impostorQuestion: string;
  /** Content pack this pair belongs to. The default family pack is "core". */
  pack: string;
  difficulty?: "easy" | "medium" | "hard";
}

/**
 * The default, family-friendly pack. An adult or themed pack can be added as a
 * separate array with pack !== "core" without mixing into this one.
 */
export const CORE_PACK: QuestionPair[] = [
  // ---------------------- العائلة (family) --------------------------------
  { id: "fam_01", category: "family", pack: "core",
    normalQuestion: "وش تحب تسوي مع العيال في الإجازة؟",
    impostorQuestion: "وش تحب تسوي مع العيال بعد المدرسة؟" },
  { id: "fam_02", category: "family", pack: "core",
    normalQuestion: "وش الشي اللي ما ينقص من بيت العائلة؟",
    impostorQuestion: "وش الشي اللي ما ينقص من مطبخ العائلة؟" },
  { id: "fam_03", category: "family", pack: "core",
    normalQuestion: "وش تجيب معك أول ما تزور بيت جدّك؟",
    impostorQuestion: "وش تجيب معك أول ما تزور بيت خالك؟" },
  { id: "fam_04", category: "family", pack: "core",
    normalQuestion: "وش أكثر غرض تتخانقون عليه بالبيت؟",
    impostorQuestion: "وش أكثر غرض تتشاركونه بالبيت؟" },
  { id: "fam_05", category: "family", pack: "core",
    normalQuestion: "وش أول سؤال تسمعه من أمك أول ما تدخل البيت؟",
    impostorQuestion: "وش أول سؤال تسمعه من أمك أول ما تصحى؟" },
  { id: "fam_06", category: "family", pack: "core",
    normalQuestion: "وش الشي اللي يجمع العائلة على طاولة وحدة؟",
    impostorQuestion: "وش الشي اللي يجمع العائلة قدام التلفزيون؟" },
  { id: "fam_07", category: "family", pack: "core",
    normalQuestion: "وش تسوي عشان ترضّي أمك؟",
    impostorQuestion: "وش تسوي عشان ترضّي أبوك؟" },
  { id: "fam_08", category: "family", pack: "core",
    normalQuestion: "وش أكثر شي تشتاق له من أيام الطفولة؟",
    impostorQuestion: "وش أكثر شي تشتاق له من أيام المدرسة؟" },
  { id: "fam_09", category: "family", pack: "core",
    normalQuestion: "وش الهدية اللي تفرّح الأم؟",
    impostorQuestion: "وش الهدية اللي تفرّح الجدّة؟" },
  { id: "fam_10", category: "family", pack: "core",
    normalQuestion: "وش تسوون لما يجي مولود جديد بالعائلة؟",
    impostorQuestion: "وش تسوون لما يتخرّج واحد من العائلة؟" },
  { id: "fam_11", category: "family", pack: "core",
    normalQuestion: "وش أكثر مكان تتصور فيه العائلة؟",
    impostorQuestion: "وش أكثر مناسبة تتصور فيها العائلة؟" },
  { id: "fam_12", category: "family", pack: "core",
    normalQuestion: "وش أول شي تسأل عنه لما تتصل بأهلك وانت مسافر؟",
    impostorQuestion: "وش أول شي تسأل عنه لما ترجع من السفر؟" },

  // ---------------------- الأصحاب (friends) -------------------------------
  { id: "frn_01", category: "friends", pack: "core",
    normalQuestion: "وش أول مكان تروحون له انت وأصحابك بالليل؟",
    impostorQuestion: "وش أول مكان تروحون له انت وأصحابك بعد الدوام؟" },
  { id: "frn_02", category: "friends", pack: "core",
    normalQuestion: "وش الشي اللي ما تطلعون بدونه مع الشلة؟",
    impostorQuestion: "وش الشي اللي ما تقعدون بدونه بالاستراحة؟" },
  { id: "frn_03", category: "friends", pack: "core",
    normalQuestion: "وش أكثر شي يأخّر الشلة عن الموعد؟",
    impostorQuestion: "وش أكثر شي يلغّي الطلعة مع الشلة؟" },
  { id: "frn_04", category: "friends", pack: "core",
    normalQuestion: "وش أكثر لعبة تلعبونها في الاستراحة؟",
    impostorQuestion: "وش أكثر لعبة تلعبونها في السيارة؟" },
  { id: "frn_05", category: "friends", pack: "core",
    normalQuestion: "وش الصفة اللي لازم تكون بصاحبك؟",
    impostorQuestion: "وش الصفة اللي ما تتحملها بصاحبك؟" },
  { id: "frn_06", category: "friends", pack: "core",
    normalQuestion: "وش أكثر شي يجمع الشلة؟",
    impostorQuestion: "وش أكثر شي يفرّق الشلة؟" },
  { id: "frn_07", category: "friends", pack: "core",
    normalQuestion: "وش أول شي تسوّيه أول ما تشوف صاحبك بعد غيبة؟",
    impostorQuestion: "وش أول شي تقوله لصاحبك بعد غيبة؟" },
  { id: "frn_08", category: "friends", pack: "core",
    normalQuestion: "وش الطلعة اللي ما تملّون منها؟",
    impostorQuestion: "وش الطلعة اللي تندمون عليها؟" },
  { id: "frn_09", category: "friends", pack: "core",
    normalQuestion: "وش أكثر شي يضحّك الشلة؟",
    impostorQuestion: "وش أكثر شي يعصّب الشلة؟" },
  { id: "frn_10", category: "friends", pack: "core",
    normalQuestion: "وش تسوّون لما يتزوّج واحد من الشلة؟",
    impostorQuestion: "وش تسوّون لما يسافر واحد من الشلة؟" },
  { id: "frn_11", category: "friends", pack: "core",
    normalQuestion: "وش تطلبون لما تقعدون في كوفي مع الشلة؟",
    impostorQuestion: "وش تطلبون لما تقعدون في مطعم مع الشلة؟" },
  { id: "frn_12", category: "friends", pack: "core",
    normalQuestion: "وش أكثر واحد بالشلة تعتمد عليه في ايش؟",
    impostorQuestion: "وش أكثر شي تعتمد فيه على أصحابك؟" },

  // ---------------------- الأكل والشرب السعودي (food) ---------------------
  { id: "fud_01", category: "food", pack: "core",
    normalQuestion: "وش أفضل شي مع الكبسة؟",
    impostorQuestion: "وش أفضل شي مع المندي؟" },
  { id: "fud_02", category: "food", pack: "core",
    normalQuestion: "وش تشرب مع القهوة؟",
    impostorQuestion: "وش تشرب مع الشاهي؟" },
  { id: "fud_03", category: "food", pack: "core",
    normalQuestion: "وش أول شي تحطه في صحن الفطور؟",
    impostorQuestion: "وش أول شي تحطه في صحن العشا؟" },
  { id: "fud_04", category: "food", pack: "core",
    normalQuestion: "وش أكثر أكلة تطلبونها لما تتكاسلون تطبخون؟",
    impostorQuestion: "وش أكثر أكلة تطبخونها بسرعة بالبيت؟" },
  { id: "fud_05", category: "food", pack: "core",
    normalQuestion: "وش تحط فوق الرز؟",
    impostorQuestion: "وش تحط فوق المعكرونة؟" },
  { id: "fud_06", category: "food", pack: "core",
    normalQuestion: "وش أفضل حلا بعد العشا؟",
    impostorQuestion: "وش أفضل حلا مع القهوة؟" },
  { id: "fud_07", category: "food", pack: "core",
    normalQuestion: "وش تطلب لما تروح مطعم لأول مرة؟",
    impostorQuestion: "وش تطلب لما ترجع لمطعمك المفضل؟" },
  { id: "fud_08", category: "food", pack: "core",
    normalQuestion: "وش النكهة اللي تختارها بالآيسكريم؟",
    impostorQuestion: "وش النكهة اللي تختارها بالميلك شيك؟" },
  { id: "fud_09", category: "food", pack: "core",
    normalQuestion: "وش تشرب في يوم حار؟",
    impostorQuestion: "وش تشرب في يوم بارد؟" },
  { id: "fud_10", category: "food", pack: "core",
    normalQuestion: "وش أفضل نوع تمر عندك؟",
    impostorQuestion: "وش أفضل نوع عسل عندك؟" },
  { id: "fud_11", category: "food", pack: "core",
    normalQuestion: "وش أكثر شي يفتح النفس قبل الأكل؟",
    impostorQuestion: "وش أكثر شي يسدّ النفس قبل الأكل؟" },
  { id: "fud_12", category: "food", pack: "core",
    normalQuestion: "وش تقدّم للضيوف مع القهوة؟",
    impostorQuestion: "وش تقدّم للجيران في صحن؟" },
  { id: "fud_13", category: "food", pack: "core",
    normalQuestion: "وش تفطر يوم الجمعة؟",
    impostorQuestion: "وش تتغدّى يوم الجمعة؟" },
  { id: "fud_14", category: "food", pack: "core",
    normalQuestion: "وش تشتري لو دخلت بقالة وانت جوعان؟",
    impostorQuestion: "وش تشتري لو دخلت بقالة وانت عطشان؟" },

  // ---------------------- المدن والسفر (travel) --------------------------
  { id: "trv_01", category: "travel", pack: "core",
    normalQuestion: "وش تاخذ معك لطلعة البر؟",
    impostorQuestion: "وش تاخذ معك للبحر؟" },
  { id: "trv_02", category: "travel", pack: "core",
    normalQuestion: "وين تحب تسافر داخل السعودية في الصيف؟",
    impostorQuestion: "وين تحب تسافر داخل السعودية في الشتاء؟" },
  { id: "trv_03", category: "travel", pack: "core",
    normalQuestion: "وش أول شي تحجزه لما تخطط لرحلة؟",
    impostorQuestion: "وش أول شي تجهّزه لما تخطط لرحلة؟" },
  { id: "trv_04", category: "travel", pack: "core",
    normalQuestion: "وش أكثر شي تنساه وانت مسافر؟",
    impostorQuestion: "وش أكثر شي تنساه وانت طالع كشتة؟" },
  { id: "trv_05", category: "travel", pack: "core",
    normalQuestion: "وين تروح لو عندك يوم واحد في الرياض؟",
    impostorQuestion: "وين تروح لو عندك يوم واحد في جدة؟" },
  { id: "trv_06", category: "travel", pack: "core",
    normalQuestion: "وش تسوّي في الطيارة عشان الوقت يمشي؟",
    impostorQuestion: "وش تسوّي في السيارة في السفرة الطويلة؟" },
  { id: "trv_07", category: "travel", pack: "core",
    normalQuestion: "وش أكثر شي يعجبك في أبها؟",
    impostorQuestion: "وش أكثر شي يعجبك في الطايف؟" },
  { id: "trv_08", category: "travel", pack: "core",
    normalQuestion: "وش تشتري لأهلك لما ترجع من سفر؟",
    impostorQuestion: "وش تشتري لنفسك لما ترجع من سفر؟" },
  { id: "trv_09", category: "travel", pack: "core",
    normalQuestion: "وش أهم شي في الفندق بالنسبة لك؟",
    impostorQuestion: "وش أهم شي في الشاليه بالنسبة لك؟" },
  { id: "trv_10", category: "travel", pack: "core",
    normalQuestion: "وين تفضل تقعد في الكشتة؟",
    impostorQuestion: "وين تفضل تقعد في المخيم؟" },
  { id: "trv_11", category: "travel", pack: "core",
    normalQuestion: "وش يخرّب عليك السفرة؟",
    impostorQuestion: "وش يخرّب عليك الطلعة؟" },
  { id: "trv_12", category: "travel", pack: "core",
    normalQuestion: "وش أول شي تشوفه في المدينة اللي تزورها؟",
    impostorQuestion: "وش أول شي تجرّبه في المدينة اللي تزورها؟" },

  // ---------------------- كرة القدم (football) --------------------------
  { id: "fut_01", category: "football", pack: "core",
    normalQuestion: "وش أهم شي في الفريق عشان يكسب؟",
    impostorQuestion: "وش أهم شي في اللاعب عشان يتميّز؟" },
  { id: "fut_02", category: "football", pack: "core",
    normalQuestion: "وش تسوّي لما يخسر فريقك؟",
    impostorQuestion: "وش تسوّي لما يفوز فريقك؟" },
  { id: "fut_03", category: "football", pack: "core",
    normalQuestion: "وش أكثر شي يعصّبك وانت تتفرّج ماتش؟",
    impostorQuestion: "وش أكثر شي يفرّحك وانت تتفرّج ماتش؟" },
  { id: "fut_04", category: "football", pack: "core",
    normalQuestion: "وين تفضّل تتابع الماتش المهم؟",
    impostorQuestion: "مع مين تفضّل تتابع الماتش المهم؟" },
  { id: "fut_05", category: "football", pack: "core",
    normalQuestion: "وش تجهّز قبل الماتش الكبير؟",
    impostorQuestion: "وش تسوّي بعد الماتش الكبير؟" },
  { id: "fut_06", category: "football", pack: "core",
    normalQuestion: "وش أهم مركز في الملعب؟",
    impostorQuestion: "وش أصعب مركز في الملعب؟" },
  { id: "fut_07", category: "football", pack: "core",
    normalQuestion: "وش أكثر شي يميّز الدوري السعودي؟",
    impostorQuestion: "وش أكثر شي يميّز كأس العالم؟" },
  { id: "fut_08", category: "football", pack: "core",
    normalQuestion: "وش تحب تلعب في الفريق؟",
    impostorQuestion: "وش ما تحب تلعب في الفريق؟" },
  { id: "fut_09", category: "football", pack: "core",
    normalQuestion: "وش أكثر شي يرفع حماس الملعب؟",
    impostorQuestion: "وش أكثر شي يوتّر جو الملعب؟" },
  { id: "fut_10", category: "football", pack: "core",
    normalQuestion: "وش تلبس لو رحت تشجّع في الملعب؟",
    impostorQuestion: "وش تاخذ معك لو رحت تشجّع في الملعب؟" },
  { id: "fut_11", category: "football", pack: "core",
    normalQuestion: "وش الشي اللي ما ينفع تفوته في الموسم؟",
    impostorQuestion: "وش الشي اللي تتمنى تحضره في الموسم؟" },
  { id: "fut_12", category: "football", pack: "core",
    normalQuestion: "وش تقول لصاحبك اللي يشجّع الفريق الثاني؟",
    impostorQuestion: "وش تقول لصاحبك بعد ما يخسر فريقه؟" },

  // ---------------------- رمضان والعيد (ramadan) ------------------------
  { id: "rmd_01", category: "ramadan", pack: "core",
    normalQuestion: "وش أول شي تفطر عليه في رمضان؟",
    impostorQuestion: "وش أول شي تتسحّر عليه في رمضان؟" },
  { id: "rmd_02", category: "ramadan", pack: "core",
    normalQuestion: "وش ما ينقص من سفرة الإفطار؟",
    impostorQuestion: "وش ما ينقص من سفرة السحور؟" },
  { id: "rmd_03", category: "ramadan", pack: "core",
    normalQuestion: "وش تسوّي بعد التراويح؟",
    impostorQuestion: "وش تسوّي قبل الإفطار بشوي؟" },
  { id: "rmd_04", category: "ramadan", pack: "core",
    normalQuestion: "وش أكثر شي تشتهيه وانت صايم؟",
    impostorQuestion: "وش أول شي تشربه أول ما تفطر؟" },
  { id: "rmd_05", category: "ramadan", pack: "core",
    normalQuestion: "وش تلبس أول يوم عيد؟",
    impostorQuestion: "وش تجهّز أول يوم عيد؟" },
  { id: "rmd_06", category: "ramadan", pack: "core",
    normalQuestion: "وش أكثر شي يميّز ليلة العيد؟",
    impostorQuestion: "وش أكثر شي يميّز صباح العيد؟" },
  { id: "rmd_07", category: "ramadan", pack: "core",
    normalQuestion: "وش تعطي العيال في العيد؟",
    impostorQuestion: "وش تتوقع تاخذ في العيد؟" },
  { id: "rmd_08", category: "ramadan", pack: "core",
    normalQuestion: "وش تجهّزون للضيوف في العيد؟",
    impostorQuestion: "وش تجهّزون للضيوف في رمضان؟" },
  { id: "rmd_09", category: "ramadan", pack: "core",
    normalQuestion: "وش أكثر مشروب على سفرة رمضان؟",
    impostorQuestion: "وش أكثر حلا على سفرة رمضان؟" },
  { id: "rmd_10", category: "ramadan", pack: "core",
    normalQuestion: "وين تروح أول أيام العيد؟",
    impostorQuestion: "وين تروح آخر أيام العيد؟" },
  { id: "rmd_11", category: "ramadan", pack: "core",
    normalQuestion: "وش تسوّي في العشر الأواخر؟",
    impostorQuestion: "وش تسوّي في أول أيام رمضان؟" },
  { id: "rmd_12", category: "ramadan", pack: "core",
    normalQuestion: "وش أكثر شي تشتاق له في رمضان؟",
    impostorQuestion: "وش أكثر شي تشتاق له في العيد؟" },

  // ---------------------- سوالف المجلس (majlis) ------------------------
  { id: "mjl_01", category: "majlis", pack: "core",
    normalQuestion: "وش أول شي يتقدّم للضيف في المجلس؟",
    impostorQuestion: "وش آخر شي يتقدّم للضيف في المجلس؟" },
  { id: "mjl_02", category: "majlis", pack: "core",
    normalQuestion: "وش أكثر موضوع تنفتح فيه السوالف بالمجلس؟",
    impostorQuestion: "وش أكثر موضوع يقفل السوالف بالمجلس؟" },
  { id: "mjl_03", category: "majlis", pack: "core",
    normalQuestion: "وش ما ينقص من جمعة العيال؟",
    impostorQuestion: "وش ما ينقص من جمعة الشباب؟" },
  { id: "mjl_04", category: "majlis", pack: "core",
    normalQuestion: "وش تسوّون في جمعة الخميس؟",
    impostorQuestion: "وش تسوّون في جمعة يوم الجمعة؟" },
  { id: "mjl_05", category: "majlis", pack: "core",
    normalQuestion: "وش يميّز المجلس الحلو؟",
    impostorQuestion: "وش يميّز الاستراحة الحلوة؟" },
  { id: "mjl_06", category: "majlis", pack: "core",
    normalQuestion: "وش أول شي تسوّيه أول ما تدخل المجلس؟",
    impostorQuestion: "وش آخر شي تسوّيه قبل ما تطلع من المجلس؟" },
  { id: "mjl_07", category: "majlis", pack: "core",
    normalQuestion: "وش تقدّمون للضيوف بعد العشا؟",
    impostorQuestion: "وش تقدّمون للضيوف قبل العشا؟" },
  { id: "mjl_08", category: "majlis", pack: "core",
    normalQuestion: "وش أكثر شي يسولف عنه كبار السن بالمجلس؟",
    impostorQuestion: "وش أكثر شي يسولف عنه الشباب بالمجلس؟" },
  { id: "mjl_09", category: "majlis", pack: "core",
    normalQuestion: "وش الشي اللي يقعّد الضيف ساعات بالمجلس؟",
    impostorQuestion: "وش الشي اللي يخلّي الضيف يستأذن بسرعة؟" },
  { id: "mjl_10", category: "majlis", pack: "core",
    normalQuestion: "وش تحطّون في وسط المجلس؟",
    impostorQuestion: "وش تحطّون في ركن المجلس؟" },
  { id: "mjl_11", category: "majlis", pack: "core",
    normalQuestion: "وش تسوّي لو صار سكوت والكل ساكت بالمجلس؟",
    impostorQuestion: "وش تسوّي لو صارت السوالف حماسية بالمجلس؟" },

  // ---------------------- الجامعة والعمل (work) ------------------------
  { id: "wrk_01", category: "work", pack: "core",
    normalQuestion: "وش أول شي تسوّيه أول ما توصل الدوام؟",
    impostorQuestion: "وش أول شي تسوّيه أول ما توصل الجامعة؟" },
  { id: "wrk_02", category: "work", pack: "core",
    normalQuestion: "وش أكثر شي يأخّرك عن الدوام؟",
    impostorQuestion: "وش أكثر شي يأخّرك عن المحاضرة؟" },
  { id: "wrk_03", category: "work", pack: "core",
    normalQuestion: "وش تشرب عشان تصحى في الدوام؟",
    impostorQuestion: "وش تشرب عشان تركّز في المذاكرة؟" },
  { id: "wrk_04", category: "work", pack: "core",
    normalQuestion: "وش أكثر شي يطفّشك في الاجتماعات؟",
    impostorQuestion: "وش أكثر شي يطفّشك في المحاضرات؟" },
  { id: "wrk_05", category: "work", pack: "core",
    normalQuestion: "وش تسوّي في بريك الدوام؟",
    impostorQuestion: "وش تسوّي في بريك المحاضرات؟" },
  { id: "wrk_06", category: "work", pack: "core",
    normalQuestion: "وش أهم شي في زميل الدوام؟",
    impostorQuestion: "وش أهم شي في زميل الدراسة؟" },
  { id: "wrk_07", category: "work", pack: "core",
    normalQuestion: "وش تجهّز ليلة قبل مقابلة عمل؟",
    impostorQuestion: "وش تجهّز ليلة قبل اختبار؟" },
  { id: "wrk_08", category: "work", pack: "core",
    normalQuestion: "وش أكثر شي يفرّحك في يوم الدوام؟",
    impostorQuestion: "وش أكثر شي يفرّحك في يوم الجامعة؟" },
  { id: "wrk_09", category: "work", pack: "core",
    normalQuestion: "وش تاخذ معك للدوام كل يوم؟",
    impostorQuestion: "وش تاخذ معك للجامعة كل يوم؟" },
  { id: "wrk_10", category: "work", pack: "core",
    normalQuestion: "وش تسوّي آخر ساعة في الدوام؟",
    impostorQuestion: "وش تسوّي آخر ساعة قبل الاختبار؟" },
  { id: "wrk_11", category: "work", pack: "core",
    normalQuestion: "وش أكثر شي يخلّيك تفكر تستقيل؟",
    impostorQuestion: "وش أكثر شي يخلّيك تفكر تغيّر تخصص؟" },
  { id: "wrk_12", category: "work", pack: "core",
    normalQuestion: "وش تحلم فيه بعد التخرّج؟",
    impostorQuestion: "وش تحلم فيه بعد ما تلقى وظيفة؟" },

  // ---------------------- أسئلة عامة خفيفة (general) --------------------
  { id: "gen_01", category: "general", pack: "core",
    normalQuestion: "وش أول شي تسوّيه أول ما تصحى؟",
    impostorQuestion: "وش آخر شي تسوّيه قبل ما تنام؟" },
  { id: "gen_02", category: "general", pack: "core",
    normalQuestion: "وش تاخذ معك لو طلعت فجأة من البيت؟",
    impostorQuestion: "وش أكثر شي تنساه لما تطلع من البيت؟" },
  { id: "gen_03", category: "general", pack: "core",
    normalQuestion: "وش أكثر تطبيق تفتحه باليوم؟",
    impostorQuestion: "وش أكثر تطبيق يضيّع وقتك؟" },
  { id: "gen_04", category: "general", pack: "core",
    normalQuestion: "وش تسوّي لما تكون زهقان؟",
    impostorQuestion: "وش تسوّي لما تكون متحمّس؟" },
  { id: "gen_05", category: "general", pack: "core",
    normalQuestion: "وش أول شي تشتريه لو ربحت مبلغ كبير؟",
    impostorQuestion: "وش أول شي تسدّده لو ربحت مبلغ كبير؟" },
  { id: "gen_06", category: "general", pack: "core",
    normalQuestion: "وش تسوّي لما تكون الدنيا ممطرة؟",
    impostorQuestion: "وش تسوّي لما تكون الدنيا حارة؟" },
  { id: "gen_07", category: "general", pack: "core",
    normalQuestion: "وش أكثر لون تلبسه؟",
    impostorQuestion: "وش أكثر لون تتجنّب تلبسه؟" },
  { id: "gen_08", category: "general", pack: "core",
    normalQuestion: "وش تسمع وانت تسوق؟",
    impostorQuestion: "وش تسمع وانت تشتغل أو تذاكر؟" },
  { id: "gen_09", category: "general", pack: "core",
    normalQuestion: "وش الشي اللي ما تعيره أحد؟",
    impostorQuestion: "وش الشي اللي ما تحب تستلفه من أحد؟" },
  { id: "gen_10", category: "general", pack: "core",
    normalQuestion: "وش أكثر شي يوتّرك؟",
    impostorQuestion: "وش أكثر شي يهدّيك؟" },
  { id: "gen_11", category: "general", pack: "core",
    normalQuestion: "وش تحب تسوّي في نهاية الأسبوع؟",
    impostorQuestion: "وش تحب تسوّي في الإجازة الطويلة؟" },
  { id: "gen_12", category: "general", pack: "core",
    normalQuestion: "وش أكثر شي تندم إنك ما سويته؟",
    impostorQuestion: "وش أكثر شي تفتخر إنك سويته؟" },
  { id: "gen_13", category: "general", pack: "core",
    normalQuestion: "وش أول شي تلاحظه في الشخص لما تقابله؟",
    impostorQuestion: "وش أول شي تتذكره عن الشخص بعد ما تقابله؟" },
];
